/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tutai.product.text.core.database;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 *
 * @author quangvh
 */
public class TextResource {

    public static final Set<Character> MARKS = new HashSet<Character>() {
        {
            add('`');
            add('~');
            add('!');
            add('@');
            add('#');
            add('$');
            add('%');
            add('^');
            add('&');
            add('*');
            add('(');
            add(')');
            add('-');
            add('_');
            add('+');
            add('=');
            add('{');
            add('[');
            add(']');
            add('}');
            add(':');
            add(';');
            add('"');
            add('\'');
            add('\\');
            add('|');
            add(',');
            add('<');
            add('.');
            add('>');
            add('/');
            add('?');
            add('•');
            add('…');
            add('￥');
            add('～');
            add('＝');
            add('；');
            add('－');
            add('）');
            add('（');
            add('★');
            add('✳');
            add('♥');
            add('上');
            add('〽');
            add('〰');
            add('】');
            add('【');
            add('✔');
            add('》');
            add('⤵');
            add('⤴');
            add('⤅');
            add('➻');
            add('➲');
            add('➯');
            add('➦');
            add('➤');
            add('➣');
            add('➢');
            add('➡');
            add('➛');
            add('❺');
            add('❹');
            add('❸');
            add('❷');
            add('❶');
            add('❤');
            add('❖');
            add('❋');
            add('❉');
            add('❇');
            add('❆');
            add('❄');
            add('❃');
            add('❂');
            add('❀');
            add('✿');
            add('✽');
            add('✺');
            add('✴');
            add('✱');
            add('✰');
            add('✯');
            add('✭');
            add('✬');
            add('✫');
            add('✪');
            add('✩');
            add('✧');
            add('✦');
            add('✥');
            add('✜');
            add('✤');
            add('✖');
            add('✓');
            add('✑');
            add('✐');
            add('✏');
            add('✌');
            add('✉');
            add('✈');
            add('✆');
            add('✂');
            add('♫');
            add('♣');
            add('♪');
            add('♨');
            add('♦');
            add('♠');
            add('♡');
            add('♛');
            add('☼');
            add('☻');
            add('☺');
            add('☸');
            add('☞');
            add('☝');
            add('☛');
            add('☑');
            add('☏');
            add('☎');
            add('☆');
            add('★');
            add('☂');
            add('☁');
            add('☀');
            add('◦');
            add('◙');
            add('◕');
            add('●');
            add('օ');
            add('○');
            add('◊');
            add('◆');
            add('◄');
            add('◀');
            add('▼');
            add('►');
            add('▸');
            add('▶');
            add('▶');
            add('▲');
            add('▬');
            add('▪');
            add('■');
            add('░');
            add('█');
            add('╬');
            add('┼');
            add('┣');
            add('═');
            add('─');
            add('ⓥ');
            add('│');
            add('☎');
            add('⊱');
            add('⑨');
            add('⑧');
            add('⑦');
            add('⑥');
            add('⑤');
            add('④');
            add('③');
            add('②');
            add('①');
            add('⌂');
            add('⋆');
            add('⊱');
            add('≧');
            add('❂');
            add('≥');
            add('≤');
            add('≡');
            add('≠');
            add('≈');
            add('∼');
            add('√');
            add('∗');
            add('−');
            add('∑');
            add('⇨');
            add('⇔');
            add('⇒');
            add('↪');
            add('↝');
            add('↙');
            add('↘');
            add('↔');
            add('→');
            add('←');
            add('⅛');
            add('⃰');
            add('€');
            add('⁃');
            add('‿');
            add('‼');
            add('※');
            add('›');
            add('‰');
            add('•');
            add('”');
            add('‡');
            add('†');
            add('“');
            add('—');
            add('–');
            add('’');
            add('‘');
            add('®');
            add('·');
            add('¶');
            add('²');
            add('´');
            add('±');
            add('°');
            add('¯');
            add('©');
            add('¬');
            add('¥');
            add('«');
            add('»');
            add('§');
            add('¦');
            add('¢');
            add('⚡');
            add('⭐');
            add('️');
            add('⚠');
            add('�');
            add('⭕');
            add('️');
            add('⚠');
            add('⭐');
            add('️');
            add('⬅');
            add('➥');
            add('➖');
            add('➕');
            add('❗');
            add('️');
            add('❗');
            add('❓');
            add('❎');
            add('❌');
            add('❁');
            add('✨');
            add('✋');
            add('✅');
            add('⛺');
            add('⛹');
            add('⛳');
            add('⛪');
            add('️');
            add('⛔');
            add('️');
            add('⚽');
            add('️');
            add('⚪');
            add('⚡');
            add('️');
            add('⚠');
            add('️');
            add('⚜');
            add('♻');
            add('️');
            add('☘');
            add('☕');
            add('□');
            add('▇');
            add('⏯');
            add('⌚');
            add('๑');
            add('۩');
            add('۞');
            add('ѻ');
            add('☘');
            add('☕');
            add('®');
            add('μ');
            add('φ');
            add('◾');
            add('☣');
            add('♐');
            add('⚓');
            add('⛱');
            add('⛲');
            add('⛽');
            add('✊');
            add('✍');
            add('✡');
            add('✵');
            add('❔');
            add('❕');
            add('❣');
            add('➽');
            add('⦁');
            add('⬇');
            add('⬆');
            add('〗');
            add('〖');
            add('・');
        }
    };

    public static final Set<String> SPACES = new HashSet<String>() {
        {
            add("\u0020");
            add("\u00A0");
            add("\u1680");
            add("\u180E");
            add("\u202F");
            add("\u205F");
            add("\u3000");
            add("\uFEFF");
            add("\u1FFF");
            add("\u2000");
            add("\u2001");
            add("\u2002");
            add("\u2003");
            add("\u2004");
            add("\u2005");
            add("\u2006");
            add("\u2007");
            add("\u2008");
            add("\u2009");
            add("\u200A");
            add("\u200B");
            add("\u200C");
            add("\u200D");
            add("\u200E");
            add("\u200F");
            add("\u1FF5");
            add("\u1FF1");
            add("\u1FF0");
            add("\u1FDC");
            add("\u1FD5");
            add("\u1FD4");
            add("\u1FC5");
            add("\u1F7F");
            add("\u1F7E");
            add("\u1F5E");
            add("\u1F5C");
            add("\u1F5A");
            add("\u1F58");
            add("\u1F4F");
            add("\u1F4E");
            add("\u1F47");
            add("\u1F46");
            add("\u1F1F");
            add("\u1F1E");
            add("\u1F17");
            add("\u1F16");
            add("\u1DFD");
            add("\u1DFC");
            add("\u1DFB");
            add("\u1DFA");
            add("\u1DF9");
            add("\u1DF8");
            add("\u1DF7");
            add("\u1DF6");
            add("\u1DF5");
            add("\u1DF4");
            add("\u1DF3");
            add("\u1DF2");
            add("\u1DF1");
            add("\u1DF0");
            add("\u1DEF");
            add("\u1DEE");
            add("\u1DED");
            add("\u1DEC");
            add("\u1DEB");
            add("\u1DEA");
            add("\u1DE9");
            add("\u1DE8");
            add("\u1DE7");
            add("\u1CFF");
            add("\u1CFE");
            add("\u1CFD");
            add("\u1CFC");
            add("\u1CFB");
            add("\u1CFA");
            add("\u1CF9");
            add("\u1CF8");
            add("\u1CF7");
            add("\u1CBF");
            add("\u1CBE");
            add("\u1CBD");
            add("\u1CBC");
            add("\u1CBB");
            add("\u1CBA");
            add("\u1CB9");
            add("\u1CB8");
            add("\u1CB7");
            add("\u1CB6");
            add("\u1CB5");
            add("\u1CB4");
            add("\u1CB3");
            add("\u1CB2");
            add("\u1CB1");
            add("\u1CB0");
            add("\u1CAF");
            add("\u1CAE");
            add("\u1CAD");
            add("\u1CAC");
            add("\u1CAB");
            add("\u1CAA");
            add("\u1CA9");
            add("\u1CA8");
            add("\u1CA7");
            add("\u1CA6");
            add("\u1CA5");
            add("\u1CA4");
            add("\u1CA3");
            add("\u1CA2");
            add("\u1CA1");
            add("\u1CA0");
            add("\u1C9F");
            add("\u1C9E");
            add("\u1C9D");
            add("\u1C9C");
            add("\u1C9B");
            add("\u1C9A");
            add("\u1C99");
            add("\u1C98");
            add("\u1C97");
            add("\u1C96");
            add("\u1C95");
            add("\u1C94");
            add("\u1C93");
            add("\u1C92");
            add("\u1C91");
            add("\u1C90");
            add("\u1C8F");
            add("\u1C8E");
            add("\u1C8D");
            add("\u1C8C");
            add("\u1C8B");
            add("\u1C8A");
            add("\u1C89");
            add("\u1C88");
            add("\u1C87");
            add("\u1C86");
            add("\u1C85");
            add("\u1C84");
            add("\u1C83");
            add("\u1C82");
            add("\u1C81");
            add("\u1C80");
            add("\u1C4C");
            add("\u1C4B");
            add("\u1C4A");
            add("\u1C3A");
            add("\u1C39");
            add("\u1C38");
            add("\u202A");
            add("\u202B");
            add("\u202C");
            add("\u202D");
            add("\u202E");
            add("\u202F");
            add("\u2065");
            add("\u2066");
            add("\u2067");
            add("\u2068");
            add("\u2069");
            add("\u2072");
            add("\u2073");
            add("\u208F");
            add("\uD83D");
            add("\uD83C");
            add("\u20AB");
            add("\uF0A7");
            add("\u0012");
            add("\u0011");
            add("\u0002");
            add("\u0004");
            add("\u0081");
            add("\u0019");
            add("\u000F");
            add("\uF0E0");
        }
    };

    public static final Map<Character, Character> MAP_SPECIAL_CHARS = new HashMap<Character, Character>() {
        {
            put('\u205A', ':');
            put('\u2055', '*');
            put('\u2053', '~');
            put('\u2052', '%');
            put('\u204F', ';');
            put('\u2045', 'E');
            put('\u2044', '/');
            put('\u2043', '-');
            put('\u203e', '-');
            put('\u2039', '<');
            put('\u203A', '>');
            put('\u2032', '\'');
            put('\u2035', '\'');
            put('\u2033', '"');
            put('\u2036', '"');
            put('\u1C50', '0');
            put('\u1C5B', 'O');
            put('\u1C79', '.');
            put('\u1C7A', ':');
            put('\u1C7B', '~');
            put('\u1C7C', '-');
            put('\u1D00', 'a');
            put('\u1D04', 'c');
            put('\u1D05', 'd');
            put('\u1D06', 'đ');
            put('\u1D07', 'e');
            put('\u1D09', '!');
            put('\u1D0A', 'j');
            put('\u1D0B', 'k');
            put('\u1D0D', 'm');
            put('\u1D0F', 'o');
            put('\u1D18', 'p');
            put('\u1D1B', 't');
            put('\u1D1C', 'u');
            put('\u1D20', 'v');
            put('\u1D21', 'w');
            put('\u1D22', 'z');
            put('\u1D29', 'P');
            put('\u1D2C', 'A');
            put('\u1D2E', 'B');
            put('\u1D30', 'D');
            put('\u1D31', 'E');
            put('\u1D33', 'G');
            put('\u1D34', 'H');
            put('\u1D35', 'I');
            put('\u1D36', 'J');
            put('\u1D37', 'K');
            put('\u1D38', 'L');
            put('\u1D39', 'M');
            put('\u1D3A', 'N');
            put('\u1D3C', 'O');
            put('\u1D3E', 'P');
            put('\u1D3F', 'R');
            put('\u1D40', 'T');
            put('\u1D41', 'U');
            put('\u1D42', 'W');
            put('\u1D43', 'a');
            put('\u1D47', 'b');
            put('\u1D48', 'd');
            put('\u1D49', 'e');
            put('\u1D4C', '3');
            put('\u1D4D', 'g');
            put('\u1D4E', '!');
            put('\u1D4F', 'k');
            put('\u1D50', 'm');
            put('\u1D52', 'o');
            put('\u1D56', 'p');
            put('\u1D57', 't');
            put('\u1D58', 'u');
            put('\u1D5B', 'v');
            put('\u1D61', 'X');
            put('\u1D62', 'i');
            put('\u1D63', 'r');
            put('\u1D64', 'u');
            put('\u1D65', 'v');
            put('\u1D6A', 'X');
            put('\u1D78', 'H');
            put('\u1D9C', 'c');
            put('\u1D9F', '3');
            put('\u1DA0', 'f');
            put('\u1DA2', 'g');
            put('\u1DAB', 'L');
            put('\u1DB0', 'N');
            put('\u1DB8', 'U');
            put('\u1DBB', 'Z');
            put('\u1DCE', '\'');
            put('\u1DDA', 'g');
            put('\u1DDB', 'G');
            put('\u1DDC', 'k');
            put('\u1DDD', 'l');
            put('\u1DDE', 'L');
            put('\u1DDF', 'M');
            put('\u1DE0', 'n');
            put('\u1DE1', 'N');
            put('\u1DE2', 'R');
            put('\u1DE3', '2');
            put('\u1DE4', 's');
            put('\u1DE5', 'f');
            put('\u1DE6', 'z');
            put('\u1DFE', '<');
            put('\u1E9A', 'ả');
            put('\u1E9C', 'f');
            put('\u1E9D', 'f');
            put('\u1FBF', '\'');
            put('\u1FCD', '"');
            put('\u1FCE', '"');
            put('\u2018', '\'');
            put('\u2019', '\'');
            put('\u1FFE', '\'');
            put('\u1FFD', '\'');
            put('\u1FEF', '\'');
            put('\u201B', '\'');
            put('\u201C', '"');
            put('\u201D', '"');
            put('\u201F', '"');
            put('\u2024', '.');
            put('\u1FDE', '"');
            put('\u1FDD', '"');
            put('\u2017', '=');
            put('\u2015', '-');
            put('\u2014', '-');
            put('\u2013', '-');
            put('\u2012', '-');
            put('\u2011', '-');
            put('\u2010', '-');
            put('\u201A', ',');
            put('\udf3a', ' ');
            put('\udc8e', ' ');
            put('\u2027', '.');
            put('\u2028', '\n');
            put('\u2029', '\n');

            put('\u0020', ' ');
            put('\u00A0', ' ');
            put('\u1680', ' ');
            put('\u180E', ' ');
            put('\u202F', ' ');
            put('\u205F', ' ');
            put('\u3000', ' ');
            put('\uFEFF', ' ');
            put('\u1FFF', ' ');
            put('\u2000', ' ');
            put('\u2001', ' ');
            put('\u2002', ' ');
            put('\u2003', ' ');
            put('\u2004', ' ');
            put('\u2005', ' ');
            put('\u2006', ' ');
            put('\u2007', ' ');
            put('\u2008', ' ');
            put('\u2009', ' ');
            put('\u200A', ' ');
            put('\u200B', ' ');
            put('\u200C', ' ');
            put('\u200D', ' ');
            put('\u200E', ' ');
            put('\u200F', ' ');
            put('\u1FF5', ' ');
            put('\u1FF1', ' ');
            put('\u1FF0', ' ');
            put('\u1FDC', ' ');
            put('\u1FD5', ' ');
            put('\u1FD4', ' ');
            put('\u1FC5', ' ');
            put('\u1F7F', ' ');
            put('\u1F7E', ' ');
            put('\u1F5E', ' ');
            put('\u1F5C', ' ');
            put('\u1F5A', ' ');
            put('\u1F58', ' ');
            put('\u1F4F', ' ');
            put('\u1F4E', ' ');
            put('\u1F47', ' ');
            put('\u1F46', ' ');
            put('\u1F1F', ' ');
            put('\u1F1E', ' ');
            put('\u1F17', ' ');
            put('\u1F16', ' ');
            put('\u1DFD', ' ');
            put('\u1DFC', ' ');
            put('\u1DFB', ' ');
            put('\u1DFA', ' ');
            put('\u1DF9', ' ');
            put('\u1DF8', ' ');
            put('\u1DF7', ' ');
            put('\u1DF6', ' ');
            put('\u1DF5', ' ');
            put('\u1DF4', ' ');
            put('\u1DF3', ' ');
            put('\u1DF2', ' ');
            put('\u1DF1', ' ');
            put('\u1DF0', ' ');
            put('\u1DEF', ' ');
            put('\u1DEE', ' ');
            put('\u1DED', ' ');
            put('\u1DEC', ' ');
            put('\u1DEB', ' ');
            put('\u1DEA', ' ');
            put('\u1DE9', ' ');
            put('\u1DE8', ' ');
            put('\u1DE7', ' ');
            put('\u1CFF', ' ');
            put('\u1CFE', ' ');
            put('\u1CFD', ' ');
            put('\u1CFC', ' ');
            put('\u1CFB', ' ');
            put('\u1CFA', ' ');
            put('\u1CF9', ' ');
            put('\u1CF8', ' ');
            put('\u1CF7', ' ');
            put('\u1CBF', ' ');
            put('\u1CBE', ' ');
            put('\u1CBD', ' ');
            put('\u1CBC', ' ');
            put('\u1CBB', ' ');
            put('\u1CBA', ' ');
            put('\u1CB9', ' ');
            put('\u1CB8', ' ');
            put('\u1CB7', ' ');
            put('\u1CB6', ' ');
            put('\u1CB5', ' ');
            put('\u1CB4', ' ');
            put('\u1CB3', ' ');
            put('\u1CB2', ' ');
            put('\u1CB1', ' ');
            put('\u1CB0', ' ');
            put('\u1CAF', ' ');
            put('\u1CAE', ' ');
            put('\u1CAD', ' ');
            put('\u1CAC', ' ');
            put('\u1CAB', ' ');
            put('\u1CAA', ' ');
            put('\u1CA9', ' ');
            put('\u1CA8', ' ');
            put('\u1CA7', ' ');
            put('\u1CA6', ' ');
            put('\u1CA5', ' ');
            put('\u1CA4', ' ');
            put('\u1CA3', ' ');
            put('\u1CA2', ' ');
            put('\u1CA1', ' ');
            put('\u1CA0', ' ');
            put('\u1C9F', ' ');
            put('\u1C9E', ' ');
            put('\u1C9D', ' ');
            put('\u1C9C', ' ');
            put('\u1C9B', ' ');
            put('\u1C9A', ' ');
            put('\u1C99', ' ');
            put('\u1C98', ' ');
            put('\u1C97', ' ');
            put('\u1C96', ' ');
            put('\u1C95', ' ');
            put('\u1C94', ' ');
            put('\u1C93', ' ');
            put('\u1C92', ' ');
            put('\u1C91', ' ');
            put('\u1C90', ' ');
            put('\u1C8F', ' ');
            put('\u1C8E', ' ');
            put('\u1C8D', ' ');
            put('\u1C8C', ' ');
            put('\u1C8B', ' ');
            put('\u1C8A', ' ');
            put('\u1C89', ' ');
            put('\u1C88', ' ');
            put('\u1C87', ' ');
            put('\u1C86', ' ');
            put('\u1C85', ' ');
            put('\u1C84', ' ');
            put('\u1C83', ' ');
            put('\u1C82', ' ');
            put('\u1C81', ' ');
            put('\u1C80', ' ');
            put('\u1C4C', ' ');
            put('\u1C4B', ' ');
            put('\u1C4A', ' ');
            put('\u1C3A', ' ');
            put('\u1C39', ' ');
            put('\u1C38', ' ');
            put('\u202A', ' ');
            put('\u202B', ' ');
            put('\u202C', ' ');
            put('\u202D', ' ');
            put('\u202E', ' ');
            put('\u202F', ' ');
            put('\u2065', ' ');
            put('\u2066', ' ');
            put('\u2067', ' ');
            put('\u2068', ' ');
            put('\u2069', ' ');
            put('\u2072', ' ');
            put('\u2073', ' ');
            put('\u208F', ' ');
            put('\uD83D', ' ');
            put('\uD83C', ' ');
            put('\u20AB', ' ');
            put('\uF0A7', ' ');
            put('\u0012', ' ');
            put('\u0011', ' ');
            put('\u0002', ' ');
            put('\u0004', ' ');
            put('\u0081', ' ');
            put('\u0019', ' ');
            put('\u000F', ' ');
            put('\uF0E0', ' ');
        }
    };

    public static Map<String, String> MAP_ENCODE_STEP_1 = new HashMap<String, String>() {
        {
            MAP_ENCODE_STEP_1.put("Ạ", "Ạ");
            MAP_ENCODE_STEP_1.put("˜a", "ã");
            MAP_ENCODE_STEP_1.put("u˜", "ũ");
            MAP_ENCODE_STEP_1.put("˜e", "ẽ");
            MAP_ENCODE_STEP_1.put("˜i", "ĩ");
            MAP_ENCODE_STEP_1.put("˜o", "õ");
            MAP_ENCODE_STEP_1.put("e˜", "ẽ");
            MAP_ENCODE_STEP_1.put("˜u", "ũ");
            MAP_ENCODE_STEP_1.put("̆a", "ă");
            MAP_ENCODE_STEP_1.put("˜y", "ỹ");
            MAP_ENCODE_STEP_1.put("U˜", "Ũ");
            MAP_ENCODE_STEP_1.put("ù", "ù");
            MAP_ENCODE_STEP_1.put("ú", "ú");
            MAP_ENCODE_STEP_1.put("ũ", "ũ");
            MAP_ENCODE_STEP_1.put("ủ", "ủ");
            MAP_ENCODE_STEP_1.put("E˜", "Ẽ");
            MAP_ENCODE_STEP_1.put("è", "è");
            MAP_ENCODE_STEP_1.put("é", "é");
            MAP_ENCODE_STEP_1.put("ê", "ê");
            MAP_ENCODE_STEP_1.put("ẽ", "ẽ");
            MAP_ENCODE_STEP_1.put("̀A", "À");
            MAP_ENCODE_STEP_1.put("ẻ", "ẻ");
            MAP_ENCODE_STEP_1.put("̀E", "È");
            MAP_ENCODE_STEP_1.put("ư", "ư");
            MAP_ENCODE_STEP_1.put("̀I", "Ì");
            MAP_ENCODE_STEP_1.put("Ù", "Ù");
            MAP_ENCODE_STEP_1.put("Ú", "Ú");
            MAP_ENCODE_STEP_1.put("o˜", "õ");
            MAP_ENCODE_STEP_1.put("Ũ", "Ũ");
            MAP_ENCODE_STEP_1.put("ụ", "ụ");
            MAP_ENCODE_STEP_1.put("̀O", "Ò");
            MAP_ENCODE_STEP_1.put("Ủ", "Ủ");
            MAP_ENCODE_STEP_1.put("̀U", "Ù");
            MAP_ENCODE_STEP_1.put("̉A", "Ả");
            MAP_ENCODE_STEP_1.put("̀Y", "Ỳ");
            MAP_ENCODE_STEP_1.put("È", "È");
            MAP_ENCODE_STEP_1.put("É", "É");
            MAP_ENCODE_STEP_1.put("̉E", "Ẻ");
            MAP_ENCODE_STEP_1.put("Ê", "Ê");
            MAP_ENCODE_STEP_1.put("Ẽ", "Ẽ");
            MAP_ENCODE_STEP_1.put("ẹ", "ẹ");
            MAP_ENCODE_STEP_1.put("́A", "Á");
            MAP_ENCODE_STEP_1.put("̉I", "Ỉ");
            MAP_ENCODE_STEP_1.put("̀a", "à");
            MAP_ENCODE_STEP_1.put("Ẻ", "Ẻ");
            MAP_ENCODE_STEP_1.put("́E", "É");
            MAP_ENCODE_STEP_1.put("̀e", "è");
            MAP_ENCODE_STEP_1.put("Ư", "Ư");
            MAP_ENCODE_STEP_1.put("̉O", "Ỏ");
            MAP_ENCODE_STEP_1.put("́I", "Í");
            MAP_ENCODE_STEP_1.put("̀i", "ì");
            MAP_ENCODE_STEP_1.put("̉U", "Ủ");
            MAP_ENCODE_STEP_1.put("O˜", "Õ");
            MAP_ENCODE_STEP_1.put("Ụ", "Ụ");
            MAP_ENCODE_STEP_1.put("́O", "Ó");
            MAP_ENCODE_STEP_1.put("̀o", "ò");
            MAP_ENCODE_STEP_1.put("̉Y", "Ỷ");
            MAP_ENCODE_STEP_1.put("ò", "ò");
            MAP_ENCODE_STEP_1.put("ó", "ó");
            MAP_ENCODE_STEP_1.put("ô", "ô");
            MAP_ENCODE_STEP_1.put("õ", "õ");
            MAP_ENCODE_STEP_1.put("́U", "Ú");
            MAP_ENCODE_STEP_1.put("̀u", "ù");
            MAP_ENCODE_STEP_1.put("̉a", "ả");
            MAP_ENCODE_STEP_1.put("́Y", "Ý");
            MAP_ENCODE_STEP_1.put("̀y", "ỳ");
            MAP_ENCODE_STEP_1.put("ỏ", "ỏ");
            MAP_ENCODE_STEP_1.put("̉e", "ẻ");
            MAP_ENCODE_STEP_1.put("Ẹ", "Ẹ");
            MAP_ENCODE_STEP_1.put("̣A", "Ạ");
            MAP_ENCODE_STEP_1.put("̂A", "Â");
            MAP_ENCODE_STEP_1.put("́a", "á");
            MAP_ENCODE_STEP_1.put("̉i", "ỉ");
            MAP_ENCODE_STEP_1.put("̣E", "Ẹ");
            MAP_ENCODE_STEP_1.put("̂E", "Ê");
            MAP_ENCODE_STEP_1.put("y˜", "ỹ");
            MAP_ENCODE_STEP_1.put("́e", "é");
            MAP_ENCODE_STEP_1.put("̉o", "ỏ");
            MAP_ENCODE_STEP_1.put("̣I", "Ị");
            MAP_ENCODE_STEP_1.put("́i", "í");
            MAP_ENCODE_STEP_1.put("̉u", "ủ");
            MAP_ENCODE_STEP_1.put("̣O", "Ọ");
            MAP_ENCODE_STEP_1.put("ơ", "ơ");
            MAP_ENCODE_STEP_1.put("̂O", "Ô");
            MAP_ENCODE_STEP_1.put("́o", "ó");
            MAP_ENCODE_STEP_1.put("̉y", "ỷ");
            MAP_ENCODE_STEP_1.put("Ò", "Ò");
            MAP_ENCODE_STEP_1.put("Ó", "Ó");
            MAP_ENCODE_STEP_1.put("̣U", "Ụ");
            MAP_ENCODE_STEP_1.put("Ô", "Ô");
            MAP_ENCODE_STEP_1.put("i˜", "ĩ");
            MAP_ENCODE_STEP_1.put("Õ", "Õ");
            MAP_ENCODE_STEP_1.put("́u", "ú");
            MAP_ENCODE_STEP_1.put("ọ", "ọ");
            MAP_ENCODE_STEP_1.put("̛O", "Ơ");
            MAP_ENCODE_STEP_1.put("̣Y", "Ỵ");
            MAP_ENCODE_STEP_1.put("́y", "ý");
            MAP_ENCODE_STEP_1.put("Ỏ", "Ỏ");
            MAP_ENCODE_STEP_1.put("̛U", "Ư");
            MAP_ENCODE_STEP_1.put("a˜", "ã");
            MAP_ENCODE_STEP_1.put("̣a", "ạ");
            MAP_ENCODE_STEP_1.put("̃A", "Ã");
            MAP_ENCODE_STEP_1.put("̂a", "â");
            MAP_ENCODE_STEP_1.put("̣e", "ẹ");
            MAP_ENCODE_STEP_1.put("̃E", "Ẽ");
            MAP_ENCODE_STEP_1.put("̂e", "ê");
            MAP_ENCODE_STEP_1.put("Y˜", "Ỹ");
            MAP_ENCODE_STEP_1.put("̣i", "ị");
            MAP_ENCODE_STEP_1.put("̃I", "Ĩ");
            MAP_ENCODE_STEP_1.put("ỳ", "ỳ");
            MAP_ENCODE_STEP_1.put("ý", "ý");
            MAP_ENCODE_STEP_1.put("ỹ", "ỹ");
            MAP_ENCODE_STEP_1.put("̣o", "ọ");
            MAP_ENCODE_STEP_1.put("Ơ", "Ơ");
            MAP_ENCODE_STEP_1.put("̃O", "Õ");
            MAP_ENCODE_STEP_1.put("̂o", "ô");
            MAP_ENCODE_STEP_1.put("ỷ", "ỷ");
            MAP_ENCODE_STEP_1.put("̣u", "ụ");
            MAP_ENCODE_STEP_1.put("̃U", "Ũ");
            MAP_ENCODE_STEP_1.put("I˜", "Ĩ");
            MAP_ENCODE_STEP_1.put("Ọ", "Ọ");
            MAP_ENCODE_STEP_1.put("̛o", "ơ");
            MAP_ENCODE_STEP_1.put("̣y", "ỵ");
            MAP_ENCODE_STEP_1.put("̃Y", "Ỹ");
            MAP_ENCODE_STEP_1.put("ì", "ì");
            MAP_ENCODE_STEP_1.put("í", "í");
            MAP_ENCODE_STEP_1.put("̛u", "ư");
            MAP_ENCODE_STEP_1.put("ĩ", "ĩ");
            MAP_ENCODE_STEP_1.put("A˜", "Ã");
            MAP_ENCODE_STEP_1.put("̃a", "ã");
            MAP_ENCODE_STEP_1.put("à", "à");
            MAP_ENCODE_STEP_1.put("á", "á");
            MAP_ENCODE_STEP_1.put("ỉ", "ỉ");
            MAP_ENCODE_STEP_1.put("â", "â");
            MAP_ENCODE_STEP_1.put("̃e", "ẽ");
            MAP_ENCODE_STEP_1.put("ã", "ã");
            MAP_ENCODE_STEP_1.put("ă", "ă");
            MAP_ENCODE_STEP_1.put("̃i", "ĩ");
            MAP_ENCODE_STEP_1.put("Ỳ", "Ỳ");
            MAP_ENCODE_STEP_1.put("Ý", "Ý");
            MAP_ENCODE_STEP_1.put("ả", "ả");
            MAP_ENCODE_STEP_1.put("Ỹ", "Ỹ");
            MAP_ENCODE_STEP_1.put("ỵ", "ỵ");
            MAP_ENCODE_STEP_1.put("̃o", "õ");
            MAP_ENCODE_STEP_1.put("Ỷ", "Ỷ");
            MAP_ENCODE_STEP_1.put("̃u", "ũ");
            MAP_ENCODE_STEP_1.put("̃y", "ỹ");
            MAP_ENCODE_STEP_1.put("Ì", "Ì");
            MAP_ENCODE_STEP_1.put("Í", "Í");
            MAP_ENCODE_STEP_1.put("Ĩ", "Ĩ");
            MAP_ENCODE_STEP_1.put("ị", "ị");
            MAP_ENCODE_STEP_1.put("À", "À");
            MAP_ENCODE_STEP_1.put("Á", "Á");
            MAP_ENCODE_STEP_1.put("Ỉ", "Ỉ");
            MAP_ENCODE_STEP_1.put("Â", "Â");
            MAP_ENCODE_STEP_1.put("ạ", "ạ");
            MAP_ENCODE_STEP_1.put("Ã", "Ã");
            MAP_ENCODE_STEP_1.put("˜A", "Ã");
            MAP_ENCODE_STEP_1.put("Ă", "Ă");
            MAP_ENCODE_STEP_1.put("Ả", "Ả");
            MAP_ENCODE_STEP_1.put("˜E", "Ẽ");
            MAP_ENCODE_STEP_1.put("Ỵ", "Ỵ");
            MAP_ENCODE_STEP_1.put("˜I", "Ĩ");
            MAP_ENCODE_STEP_1.put("˜O", "Õ");
            MAP_ENCODE_STEP_1.put("˜U", "Ũ");
            MAP_ENCODE_STEP_1.put("Ị", "Ị");
            MAP_ENCODE_STEP_1.put("̆A", "Ă");
            MAP_ENCODE_STEP_1.put("˜Y", "Ỹ");
        }
    };

    public final static Map<String, String> MAP_ENCODE_STEP_2 = new HashMap<String, String>() {
        {
            put("̂Ã", "Ẫ");
            put("́â", "ấ");
            put("̀Ă", "Ằ");
            put("̀ă", "ằ");
            put("̂È", "Ề");
            put("̂É", "Ế");
            put("̣Ê", "Ệ");
            put("́ê", "ế");
            put("̂Ọ", "Ộ");
            put("̂ọ", "ộ");
            put("̂Ỏ", "Ổ");
            put("̂ỏ", "ổ");
            put("Ở", "Ở");
            put("̂Ò", "Ồ");
            put("ỏ̂", "ổ");
            put("̂Ó", "Ố");
            put("̣Ô", "Ộ");
            put("̂Õ", "Ỗ");
            put("́ô", "ố");
            put("Ă˜", "Ẵ");
            put("̂à", "ầ");
            put("̂á", "ấ");
            put("̃Â", "Ẫ");
            put("̣â", "ậ");
            put("̂ã", "ẫ");
            put("́Ă", "Ắ");
            put("́ă", "ắ");
            put("à̂", "ầ");
            put("̂è", "ề");
            put("à̆", "ằ");
            put("̂é", "ế");
            put("̣ê", "ệ");
            put("̃Ê", "Ễ");
            put("ở", "ở");
            put("̂ò", "ồ");
            put("̂ó", "ố");
            put("̣ô", "ộ");
            put("̃Ô", "Ỗ");
            put("̂õ", "ỗ");
            put("ă˜", "ẵ");
            put("â˜", "ẫ");
            put("Ằ", "Ằ");
            put("̃â", "ẫ");
            put("Ắ", "Ắ");
            put("̣Ă", "Ặ");
            put("̣ă", "ặ");
            put("á̂", "ấ");
            put("Ẵ", "Ẵ");
            put("À̂", "Ầ");
            put("˜Ơ", "Ỡ");
            put("˜ơ", "ỡ");
            put("á̆", "ắ");
            put("À̆", "Ằ");
            put("̃ê", "ễ");
            put("Ẳ", "Ẳ");
            put("ò̂", "ồ");
            put("̃ô", "ỗ");
            put("˜Ư", "Ữ");
            put("˜ư", "ữ");
            put("Â˜", "Ẫ");
            put("̆Ạ", "Ặ");
            put("̆ạ", "ặ");
            put("̆Ả", "Ẳ");
            put("ằ", "ằ");
            put("̆ả", "ẳ");
            put("ắ", "ắ");
            put("ầ", "ầ");
            put("ấ", "ấ");
            put("̃Ă", "Ẵ");
            put("ẵ", "ẵ");
            put("̃ă", "ẵ");
            put("Á̂", "Ấ");
            put("Ậ", "Ậ");
            put("ẫ", "ẫ");
            put("Ặ", "Ặ");
            put("Á̆", "Ắ");
            put("Ặ", "Ặ");
            put("ẳ", "ẳ");
            put("ẩ", "ẩ");
            put("ô˜", "ỗ");
            put("ờ", "ờ");
            put("ó̂", "ố");
            put("Ò̂", "Ồ");
            put("̆À", "Ằ");
            put("̆Á", "Ắ");
            put("̆Ã", "Ẵ");
            put("Ầ", "Ầ");
            put("Ấ", "Ấ");
            put("ã̂", "ẫ");
            put("ặ", "ặ");
            put("Ẫ", "Ẫ");
            put("ậ", "ậ");
            put("ậ", "ậ");
            put("ã̆", "ẵ");
            put("ặ", "ặ");
            put("Ẩ", "Ẩ");
            put("Ô˜", "Ỗ");
            put("ớ", "ớ");
            put("Ờ", "Ờ");
            put("ồ", "ồ");
            put("ố", "ố");
            put("Ó̂", "Ố");
            put("ỗ", "ỗ");
            put("ổ", "ổ");
            put("̆à", "ằ");
            put("̆á", "ắ");
            put("̆ã", "ẵ");
            put("Ã̂", "Ẫ");
            put("̀Ơ", "Ờ");
            put("Ậ", "Ậ");
            put("̀ơ", "ờ");
            put("Ã̆", "Ẵ");
            put("Ả̂", "Ẩ");
            put("Ả̆", "Ẳ");
            put("Ớ", "Ớ");
            put("Ồ", "Ồ");
            put("Ố", "Ố");
            put("õ̂", "ỗ");
            put("Ỗ", "Ỗ");
            put("ộ", "ộ");
            put("̀Ư", "Ừ");
            put("̀ư", "ừ");
            put("Ữ", "Ữ");
            put("Ự", "Ự");
            put("Ổ", "Ổ");
            put("ả̂", "ẩ");
            put("́Ơ", "Ớ");
            put("ả̆", "ẳ");
            put("́ơ", "ớ");
            put("ỡ", "ỡ");
            put("Õ̂", "Ỗ");
            put("́Ư", "Ứ");
            put("Ộ", "Ộ");
            put("́ư", "ứ");
            put("ữ", "ữ");
            put("ự", "ự");
            put("̉Â", "Ẩ");
            put("̣Ơ", "Ợ");
            put("̣ơ", "ợ");
            put("̉Ê", "Ể");
            put("Ỡ", "Ỡ");
            put("̉Ô", "Ổ");
            put("̣Ư", "Ự");
            put("̣ư", "ự");
            put("Ử", "Ử");
            put("̉â", "ẩ");
            put("̃Ơ", "Ỡ");
            put("̃ơ", "ỡ");
            put("̉ê", "ể");
            put("̉ô", "ổ");
            put("̃Ư", "Ữ");
            put("̃ư", "ữ");
            put("Ư˜", "Ữ");
            put("̛Ọ", "Ợ");
            put("̛ọ", "ợ");
            put("̛Ỏ", "Ở");
            put("̛ỏ", "ở");
            put("ử", "ử");
            put("̛Ò", "Ờ");
            put("̛Ó", "Ớ");
            put("̉Ă", "Ẳ");
            put("̉ă", "ẳ");
            put("è̂", "ề");
            put("̛Õ", "Ỡ");
            put("̛Ù", "Ừ");
            put("̛Ú", "Ứ");
            put("̛Ụ", "Ự");
            put("̛ụ", "ự");
            put("̛Ủ", "Ử");
            put("ư˜", "ữ");
            put("̛ủ", "ử");
            put("Ừ", "Ừ");
            put("ê˜", "ễ");
            put("Ứ", "Ứ");
            put("Ữ", "Ữ");
            put("̛ò", "ờ");
            put("̛ó", "ớ");
            put("é̂", "ế");
            put("È̂", "Ề");
            put("̛õ", "ỡ");
            put("Ử", "Ử");
            put("Ơ˜", "Ỡ");
            put("̛ù", "ừ");
            put("̛ú", "ứ");
            put("ừ", "ừ");
            put("Ệ", "Ệ");
            put("ừ", "ừ");
            put("ứ", "ứ");
            put("Ê˜", "Ễ");
            put("ữ", "ữ");
            put("Ự", "Ự");
            put("ề", "ề");
            put("ế", "ế");
            put("É̂", "Ế");
            put("ử", "ử");
            put("ễ", "ễ");
            put("ơ˜", "ỡ");
            put("ể", "ể");
            put("Ờ", "Ờ");
            put("Ớ", "Ớ");
            put("ứ", "ứ");
            put("Ừ", "Ừ");
            put("Ỡ", "Ỡ");
            put("˜Â", "Ẫ");
            put("Ở", "Ở");
            put("ệ", "ệ");
            put("˜Ê", "Ễ");
            put("ự", "ự");
            put("Ề", "Ề");
            put("Ế", "Ế");
            put("˜Ô", "Ỗ");
            put("Ễ", "Ễ");
            put("ệ", "ệ");
            put("Ể", "Ể");
            put("ờ", "ờ");
            put("ớ", "ớ");
            put("Ứ", "Ứ");
            put("ỡ", "ỡ");
            put("Ợ", "Ợ");
            put("˜â", "ẫ");
            put("ở", "ở");
            put("Ẻ̂", "Ể");
            put("˜ê", "ễ");
            put("˜ô", "ỗ");
            put("Ệ", "Ệ");
            put("ợ", "ợ");
            put("ẻ̂", "ể");
            put("˜Ă", "Ẵ");
            put("˜ă", "ẵ");
            put("̛Ũ", "Ữ");
            put("̛ũ", "ữ");
            put("Ộ", "Ộ");
            put("̉Ơ", "Ở");
            put("̉ơ", "ở");
            put("̀Â", "Ầ");
            put("Ẽ̂", "Ễ");
            put("̉Ư", "Ử");
            put("̉ư", "ử");
            put("̀Ê", "Ề");
            put("Ợ", "Ợ");
            put("̀Ô", "Ồ");
            put("ộ", "ộ");
            put("̂Ạ", "Ậ");
            put("̂ạ", "ậ");
            put("̂Ả", "Ẩ");
            put("́Â", "Ấ");
            put("̂ả", "ẩ");
            put("̀â", "ầ");
            put("ẽ̂", "ễ");
            put("́Ê", "Ế");
            put("̀ê", "ề");
            put("ợ", "ợ");
            put("́Ô", "Ố");
            put("̀ô", "ồ");
            put("̂Ẹ", "Ệ");
            put("Ỏ̂", "Ổ");
            put("̂ẹ", "ệ");
            put("̂Ẻ", "Ể");
            put("̂ẻ", "ể");
            put("̂Ẽ", "Ễ");
            put("̂ẽ", "ễ");
            put("̂À", "Ầ");
            put("̂Á", "Ấ");
            put("̣Â", "Ậ");
        }
    };

    public final static Map<String, String> VOWAL_AUTO_CORRECT_STEP_1 = new HashMap<String, String>() {
        {
            put("eọ", "ẹo");
            put("EỌ", "ẸO");
            put("Eọ", "Ẹo");
            put("eỌ", "ẹO");
            put("ùâ", "uầ");
            put("ÙÂ", "UẦ");
            put("Ùâ", "Uầ");
            put("ùÂ", "uẦ");
            put("eỏ", "ẻo");
            put("EỎ", "ẺO");
            put("Eỏ", "Ẻo");
            put("eỎ", "ẻO");
            put("uà", "ùa");
            put("UÀ", "ÙA");
            put("Uà", "Ùa");
            put("uÀ", "ùA");
            put("uá", "úa");
            put("UÁ", "ÚA");
            put("Uá", "Úa");
            put("uÁ", "úA");
            put("uã", "ũa");
            put("UÃ", "ŨA");
            put("Uã", "Ũa");
            put("uÃ", "ũA");
            put("ùê", "uề");
            put("ÙÊ", "UỀ");
            put("Ùê", "Uề");
            put("ùÊ", "uỀ");
            put("oạ", "ọa");
            put("OẠ", "ỌA");
            put("Oạ", "Ọa");
            put("oẠ", "ọA");
            put("oả", "ỏa");
            put("OẢ", "ỎA");
            put("Oả", "Ỏa");
            put("oẢ", "ỏA");
            put("ừơ", "ườ");
            put("ỪƠ", "ƯỜ");
            put("Ừơ", "Ườ");
            put("ừƠ", "ưỜ");
            put("ỏă", "oẳ");
            put("ỎĂ", "OẲ");
            put("Ỏă", "Oẳ");
            put("ỏĂ", "oẲ");
            put("uì", "ùi");
            put("UÌ", "ÙI");
            put("Uì", "Ùi");
            put("uÌ", "ùI");
            put("uí", "úi");
            put("UÍ", "ÚI");
            put("Uí", "Úi");
            put("uÍ", "úI");
            put("ưỉ", "ửi");
            put("ƯỈ", "ỬI");
            put("Ưỉ", "Ửi");
            put("ưỈ", "ửI");
            put("ưị", "ựi");
            put("ƯỊ", "ỰI");
            put("Ưị", "Ựi");
            put("ưỊ", "ựI");
            put("ùô", "uồ");
            put("ÙÔ", "UỒ");
            put("Ùô", "Uồ");
            put("ùÔ", "uỒ");
            put("uỳ", "ùy");
            put("UỲ", "ÙY");
            put("Uỳ", "Ùy");
            put("uỲ", "ùY");
            put("iũ", "ĩu");
            put("IŨ", "ĨU");
            put("Iũ", "Ĩu");
            put("iŨ", "ĩU");
            put("uỵ", "ụy");
            put("UỴ", "ỤY");
            put("Uỵ", "Ụy");
            put("uỴ", "ụY");
            put("uỷ", "ủy");
            put("UỶ", "ỦY");
            put("Uỷ", "Ủy");
            put("uỶ", "ủY");
            put("uỹ", "ũy");
            put("UỸ", "ŨY");
            put("Uỹ", "Ũy");
            put("uỸ", "ũY");
            put("aũ", "ãu");
            put("AŨ", "ÃU");
            put("Aũ", "Ãu");
            put("aŨ", "ãU");
            put("úâ", "uấ");
            put("ÚÂ", "UẤ");
            put("Úâ", "Uấ");
            put("úÂ", "uẤ");
            put("uý", "úy");
            put("UÝ", "ÚY");
            put("Uý", "Úy");
            put("uÝ", "úY");
            put("oẹ", "ọe");
            put("OẸ", "ỌE");
            put("Oẹ", "Ọe");
            put("oẸ", "ọE");
            put("oẻ", "ỏe");
            put("OẺ", "ỎE");
            put("Oẻ", "Ỏe");
            put("oẺ", "ỏE");
            put("eò", "èo");
            put("EÒ", "ÈO");
            put("Eò", "Èo");
            put("eÒ", "èO");
            put("eó", "éo");
            put("EÓ", "ÉO");
            put("Eó", "Éo");
            put("eÓ", "éO");
            put("oẽ", "õe");
            put("OẼ", "ÕE");
            put("Oẽ", "Õe");
            put("oẼ", "õE");
            put("ưở", "ưở");
            put("ƯỞ", "ƯỞ");
            put("Ưở", "Ưở");
            put("ưỞ", "ưỞ");
            put("eõ", "ẽo");
            put("EÕ", "ẼO");
            put("Eõ", "Ẽo");
            put("eÕ", "ẽO");
            put("ưà", "ừa");
            put("ƯÀ", "ỪA");
            put("Ưà", "Ừa");
            put("ưÀ", "ừA");
            put("úê", "uế");
            put("ÚÊ", "UẾ");
            put("Úê", "Uế");
            put("úÊ", "uẾ");
            put("ưá", "ứa");
            put("ƯÁ", "ỨA");
            put("Ưá", "Ứa");
            put("ưÁ", "ứA");
            put("ưã", "ữa");
            put("ƯÃ", "ỮA");
            put("Ưã", "Ữa");
            put("ưÃ", "ữA");
            put("ưụ", "ựu");
            put("ƯỤ", "ỰU");
            put("Ưụ", "Ựu");
            put("ưỤ", "ựU");
            put("ưủ", "ửu");
            put("ƯỦ", "ỬU");
            put("Ưủ", "Ửu");
            put("ưỦ", "ửU");
            put("oỉ", "ỏi");
            put("OỈ", "ỎI");
            put("Oỉ", "Ỏi");
            put("oỈ", "ỏI");
            put("úô", "uố");
            put("ÚÔ", "UỐ");
            put("Úô", "Uố");
            put("úÔ", "uỐ");
            put("êụ", "ệu");
            put("ÊỤ", "ỆU");
            put("Êụ", "Ệu");
            put("êỤ", "ệU");
            put("oị", "ọi");
            put("OỊ", "ỌI");
            put("Oị", "Ọi");
            put("oỊ", "ọI");
            put("ưì", "ừi");
            put("ƯÌ", "ỪI");
            put("Ưì", "Ừi");
            put("ưÌ", "ừI");
            put("êủ", "ểu");
            put("ÊỦ", "ỂU");
            put("Êủ", "Ểu");
            put("êỦ", "ểU");
            put("ưí", "ứi");
            put("ƯÍ", "ỨI");
            put("Ưí", "Ứi");
            put("ưÍ", "ứI");
            put("ỉê", "iể");
            put("ỈÊ", "IỂ");
            put("Ỉê", "Iể");
            put("ỉÊ", "iỂ");
            put("âụ", "ậu");
            put("ÂỤ", "ẬU");
            put("Âụ", "Ậu");
            put("âỤ", "ậU");
            put("âủ", "ẩu");
            put("ÂỦ", "ẨU");
            put("Âủ", "Ẩu");
            put("âỦ", "ẩU");
            put("ơỉ", "ởi");
            put("ƠỈ", "ỞI");
            put("Ơỉ", "Ởi");
            put("ơỈ", "ởI");
            put("ưù", "ừu");
            put("ƯÙ", "ỪU");
            put("Ưù", "Ừu");
            put("ưÙ", "ừU");
            put("ơị", "ợi");
            put("ƠỊ", "ỢI");
            put("Ơị", "Ợi");
            put("ơỊ", "ợI");
            put("ưú", "ứu");
            put("ƯÚ", "ỨU");
            put("Ưú", "Ứu");
            put("ưÚ", "ứU");
            put("êù", "ều");
            put("ÊÙ", "ỀU");
            put("Êù", "Ều");
            put("êÙ", "ềU");
            put("êú", "ếu");
            put("ÊÚ", "ẾU");
            put("Êú", "Ếu");
            put("êÚ", "ếU");
            put("âỳ", "ầy");
            put("ÂỲ", "ẦY");
            put("Âỳ", "Ầy");
            put("âỲ", "ầY");
            put("oà", "òa");
            put("OÀ", "ÒA");
            put("Oà", "Òa");
            put("oÀ", "òA");
            put("òă", "oằ");
            put("ÒĂ", "OẰ");
            put("Òă", "Oằ");
            put("òĂ", "oẰ");
            put("oá", "óa");
            put("OÁ", "ÓA");
            put("Oá", "Óa");
            put("oÁ", "óA");
            put("âỵ", "ậy");
            put("ÂỴ", "ẬY");
            put("Âỵ", "Ậy");
            put("âỴ", "ậY");
            put("oã", "õa");
            put("OÃ", "ÕA");
            put("Oã", "Õa");
            put("oÃ", "õA");
            put("uĩ", "ũi");
            put("UĨ", "ŨI");
            put("Uĩ", "Ũi");
            put("uĨ", "ũI");
            put("âỷ", "ẩy");
            put("ÂỶ", "ẨY");
            put("Âỷ", "Ẩy");
            put("âỶ", "ẩY");
            put("ôỉ", "ổi");
            put("ÔỈ", "ỔI");
            put("Ôỉ", "Ổi");
            put("ôỈ", "ổI");
            put("âù", "ầu");
            put("ÂÙ", "ẦU");
            put("Âù", "Ầu");
            put("âÙ", "ầU");
            put("âỹ", "ẫy");
            put("ÂỸ", "ẪY");
            put("Âỹ", "Ẫy");
            put("âỸ", "ẫY");
            put("ôị", "ội");
            put("ÔỊ", "ỘI");
            put("Ôị", "Ội");
            put("ôỊ", "ộI");
            put("âú", "ấu");
            put("ÂÚ", "ẤU");
            put("Âú", "Ấu");
            put("âÚ", "ấU");
            put("iạ", "ịa");
            put("IẠ", "ỊA");
            put("Iạ", "Ịa");
            put("iẠ", "ịA");
            put("ũơ", "uỡ");
            put("ŨƠ", "UỠ");
            put("Ũơ", "Uỡ");
            put("ũƠ", "uỠ");
            put("oè", "òe");
            put("OÈ", "ÒE");
            put("Oè", "Òe");
            put("oÈ", "òE");
            put("iả", "ỉa");
            put("IẢ", "ỈA");
            put("Iả", "Ỉa");
            put("iẢ", "ỉA");
            put("oé", "óe");
            put("OÉ", "ÓE");
            put("Oé", "Óe");
            put("oÉ", "óE");
            put("âý", "ấy");
            put("ÂÝ", "ẤY");
            put("Âý", "Ấy");
            put("âÝ", "ấY");
            put("oì", "òi");
            put("OÌ", "ÒI");
            put("Oì", "Òi");
            put("oÌ", "òI");
            put("oí", "ói");
            put("OÍ", "ÓI");
            put("Oí", "Ói");
            put("oÍ", "óI");
            put("ụơ", "uợ");
            put("ỤƠ", "UỢ");
            put("Ụơ", "Uợ");
            put("ụƠ", "uỢ");
            put("ơì", "ời");
            put("ƠÌ", "ỜI");
            put("Ơì", "Ời");
            put("ơÌ", "ờI");
            put("ơí", "ới");
            put("ƠÍ", "ỚI");
            put("Ơí", "Ới");
            put("ơÍ", "ớI");
            put("óă", "oắ");
            put("ÓĂ", "OẮ");
            put("Óă", "Oắ");
            put("óĂ", "oẮ");
            put("ôì", "ồi");
            put("ÔÌ", "ỒI");
            put("Ôì", "Ồi");
            put("ôÌ", "ồI");
            put("ôí", "ối");
            put("ÔÍ", "ỐI");
            put("Ôí", "Ối");
            put("ôÍ", "ốI");
            put("ưĩ", "ữi");
            put("ƯĨ", "ỮI");
            put("Ưĩ", "Ữi");
            put("ưĨ", "ữI");
            put("ịê", "iệ");
            put("ỊÊ", "IỆ");
            put("Ịê", "Iệ");
            put("ịÊ", "iỆ");
            put("ìê", "iề");
            put("ÌÊ", "IỀ");
            put("Ìê", "Iề");
            put("ìÊ", "iỀ");
            put("aỉ", "ải");
            put("AỈ", "ẢI");
            put("Aỉ", "Ải");
            put("aỈ", "ảI");
            put("aị", "ại");
            put("AỊ", "ẠI");
            put("Aị", "Ại");
            put("aỊ", "ạI");
            put("aọ", "ạo");
            put("AỌ", "ẠO");
            put("Aọ", "Ạo");
            put("aỌ", "ạO");
            put("aỏ", "ảo");
            put("AỎ", "ẢO");
            put("Aỏ", "Ảo");
            put("aỎ", "ảO");
            put("ữơ", "ưỡ");
            put("ỮƠ", "ƯỠ");
            put("Ữơ", "Ưỡ");
            put("ữƠ", "ưỠ");
            put("ià", "ìa");
            put("IÀ", "ÌA");
            put("Ià", "Ìa");
            put("iÀ", "ìA");
            put("iá", "ía");
            put("IÁ", "ÍA");
            put("Iá", "Ía");
            put("iÁ", "íA");
            put("ũâ", "uẫ");
            put("ŨÂ", "UẪ");
            put("Ũâ", "Uẫ");
            put("ũÂ", "uẪ");
            put("ủơ", "uở");
            put("ỦƠ", "UỞ");
            put("Ủơ", "Uở");
            put("ủƠ", "uỞ");
            put("iã", "ĩa");
            put("IÃ", "ĨA");
            put("Iã", "Ĩa");
            put("iÃ", "ĩA");
            put("oĩ", "õi");
            put("OĨ", "ÕI");
            put("Oĩ", "Õi");
            put("oĨ", "õI");
            put("iụ", "ịu");
            put("IỤ", "ỊU");
            put("Iụ", "Ịu");
            put("iỤ", "ịU");
            put("íê", "iế");
            put("ÍÊ", "IẾ");
            put("Íê", "Iế");
            put("íÊ", "iẾ");
            put("iủ", "ỉu");
            put("IỦ", "ỈU");
            put("Iủ", "Ỉu");
            put("iỦ", "ỉU");
            put("ụâ", "uậ");
            put("ỤÂ", "UẬ");
            put("Ụâ", "Uậ");
            put("ụÂ", "uẬ");
            put("ũê", "uễ");
            put("ŨÊ", "UỄ");
            put("Ũê", "Uễ");
            put("ũÊ", "uỄ");
            put("aụ", "ạu");
            put("AỤ", "ẠU");
            put("Aụ", "Ạu");
            put("aỤ", "ạU");
            put("aủ", "ảu");
            put("AỦ", "ẢU");
            put("Aủ", "Ảu");
            put("aỦ", "ảU");
            put("ụê", "uệ");
            put("ỤÊ", "UỆ");
            put("Ụê", "Uệ");
            put("ụÊ", "uỆ");
            put("ơĩ", "ỡi");
            put("ƠĨ", "ỠI");
            put("Ơĩ", "Ỡi");
            put("ơĨ", "ỡI");
            put("aì", "ài");
            put("AÌ", "ÀI");
            put("Aì", "Ài");
            put("aÌ", "àI");
            put("ũô", "uỗ");
            put("ŨÔ", "UỖ");
            put("Ũô", "Uỗ");
            put("ũÔ", "uỖ");
            put("aí", "ái");
            put("AÍ", "ÁI");
            put("Aí", "Ái");
            put("aÍ", "áI");
            put("ụô", "uộ");
            put("ỤÔ", "UỘ");
            put("Ụô", "Uộ");
            put("ụÔ", "uỘ");
            put("õă", "oẵ");
            put("ÕĂ", "OẴ");
            put("Õă", "Oẵ");
            put("õĂ", "oẴ");
            put("iù", "ìu");
            put("IÙ", "ÌU");
            put("Iù", "Ìu");
            put("iÙ", "ìU");
            put("aò", "ào");
            put("AÒ", "ÀO");
            put("Aò", "Ào");
            put("aÒ", "àO");
            put("iú", "íu");
            put("IÚ", "ÍU");
            put("Iú", "Íu");
            put("iÚ", "íU");
            put("aó", "áo");
            put("AÓ", "ÁO");
            put("Aó", "Áo");
            put("aÓ", "áO");
            put("aỳ", "ày");
            put("AỲ", "ÀY");
            put("Aỳ", "Ày");
            put("aỲ", "àY");
            put("aõ", "ão");
            put("AÕ", "ÃO");
            put("Aõ", "Ão");
            put("aÕ", "ãO");
            put("aỵ", "ạy");
            put("AỴ", "ẠY");
            put("Aỵ", "Ạy");
            put("aỴ", "ạY");
            put("ôĩ", "ỗi");
            put("ÔĨ", "ỖI");
            put("Ôĩ", "Ỗi");
            put("ôĨ", "ỗI");
            put("aỷ", "ảy");
            put("AỶ", "ẢY");
            put("Aỷ", "Ảy");
            put("aỶ", "ảY");
            put("aù", "àu");
            put("AÙ", "ÀU");
            put("Aù", "Àu");
            put("aÙ", "àU");
            put("aỹ", "ãy");
            put("AỸ", "ÃY");
            put("Aỹ", "Ãy");
            put("aỸ", "ãY");
            put("aú", "áu");
            put("AÚ", "ÁU");
            put("Aú", "Áu");
            put("aÚ", "áU");
            put("ưũ", "ữu");
            put("ƯŨ", "ỮU");
            put("Ưũ", "Ữu");
            put("ưŨ", "ữU");
            put("aý", "áy");
            put("AÝ", "ÁY");
            put("Aý", "Áy");
            put("aÝ", "áY");
            put("êũ", "ễu");
            put("ÊŨ", "ỄU");
            put("Êũ", "Ễu");
            put("êŨ", "ễU");
            put("âũ", "ẫu");
            put("ÂŨ", "ẪU");
            put("Âũ", "Ẫu");
            put("âŨ", "ẫU");
            put("ùơ", "uờ");
            put("ÙƠ", "UỜ");
            put("Ùơ", "Uờ");
            put("ùƠ", "uỜ");
            put("uạ", "ụa");
            put("UẠ", "ỤA");
            put("Uạ", "Ụa");
            put("uẠ", "ụA");
            put("uả", "ủa");
            put("UẢ", "ỦA");
            put("Uả", "Ủa");
            put("uẢ", "ủA");
            put("ựơ", "ượ");
            put("ỰƠ", "ƯỢ");
            put("Ựơ", "Ượ");
            put("ựƠ", "ưỢ");
            put("ọă", "oặ");
            put("ỌĂ", "OẶ");
            put("Ọă", "Oặ");
            put("ọĂ", "oẶ");
            put("ủâ", "uẩ");
            put("ỦÂ", "UẨ");
            put("Ủâ", "Uẩ");
            put("ủÂ", "uẨ");
            put("ứơ", "ướ");
            put("ỨƠ", "ƯỚ");
            put("Ứơ", "Ướ");
            put("ứƠ", "ưỚ");
            put("ủê", "uể");
            put("ỦÊ", "UỂ");
            put("Ủê", "Uể");
            put("ủÊ", "uỂ");
            put("ĩê", "iễ");
            put("ĨÊ", "IỄ");
            put("Ĩê", "Iễ");
            put("ĩÊ", "iỄ");
            put("úơ", "uớ");
            put("ÚƠ", "UỚ");
            put("Úơ", "Uớ");
            put("úƠ", "uỚ");
            put("aĩ", "ãi");
            put("AĨ", "ÃI");
            put("Aĩ", "Ãi");
            put("aĨ", "ãI");
            put("ủô", "uổ");
            put("ỦÔ", "UỔ");
            put("Ủô", "Uổ");
            put("ủÔ", "uỔ");
            put("ưạ", "ựa");
            put("ƯẠ", "ỰA");
            put("Ưạ", "Ựa");
            put("ưẠ", "ựA");
            put("ưả", "ửa");
            put("ƯẢ", "ỬA");
            put("Ưả", "Ửa");
            put("ưẢ", "ửA");
            put("uỉ", "ủi");
            put("UỈ", "ỦI");
            put("Uỉ", "Ủi");
            put("uỈ", "ủI");
            put("uị", "ụi");
            put("UỊ", "ỤI");
            put("Uị", "Ụi");
            put("uỊ", "ụI");
        }
    };

    public final static Map<String, String> VOWAL_AUTO_CORRECT_STEP_2 = new HashMap<String, String>() {
        {
            put("UỸê", "UYễ");
            put("uỸÊ", "uYỄ");
            put("UỹÊ", "UyỄ");
            put("Ọep", "Oẹp");
            put("Ọen", "Oẹn");
            put("Ọet", "Oẹt");
            put("úYnH", "uÝnH");
            put("uỷê", "uyể");
            put("ỦYN", "UỶN");
            put("yÊŨ", "yỄU");
            put("ĨÊu", "IỄu");
            put("Ọec", "Oẹc");
            put("ỦYA", "UỶA");
            put("Ùynh", "Uỳnh");
            put("Uỹê", "Uyễ");
            put("ỌeP", "OẹP");
            put("ỌeN", "OẹN");
            put("ùYNh", "uỲNh");
            put("ỌeT", "OẹT");
            put("ùyNH", "uỳNH");
            put("ÚôI", "UốI");
            put("ÓAC", "OÁC");
            put("ÓAI", "OÁI");
            put("ỌeC", "OẹC");
            put("ÕEN", "OẼN");
            put("ÙYnh", "UỲnh");
            put("ÙynH", "UỳnH");
            put("ÓAP", "OÁP");
            put("uỹê", "uyễ");
            put("ÓAN", "OÁN");
            put("ọEN", "oẸN");
            put("ÓAT", "OÁT");
            put("ùYNH", "uỲNH");
            put("ủyn", "uỷn");
            put("ÓAY", "OÁY");
            put("ọEP", "oẸP");
            put("Úôi", "Uối");
            put("ọET", "oẸT");
            put("ÓAc", "OÁc");
            put("óAC", "oÁC");
            put("ÓAi", "OÁi");
            put("óAI", "oÁI");
            put("ọEC", "oẸC");
            put("ÒaI", "OàI");
            put("ủya", "uỷa");
            put("ÒaN", "OàN");
            put("ÕEn", "OẼn");
            put("õEN", "oẼN");
            put("ÙYnH", "UỲnH");
            put("ÓAp", "OÁp");
            put("óAP", "oÁP");
            put("ÓAn", "OÁn");
            put("óAN", "oÁN");
            put("ỤYNH", "UỴNH");
            put("ÓAt", "OÁt");
            put("óAT", "oÁT");
            put("ÓAy", "OÁy");
            put("óAY", "oÁY");
            put("ÒaY", "OàY");
            put("úôi", "uối");
            put("Ọay", "Oạy");
            put("Òai", "Oài");
            put("UYạ", "UỴa");
            put("Òan", "Oàn");
            put("UYẠ", "UỴA");
            put("UYả", "UỶa");
            put("UYẢ", "UỶA");
            put("ỦYÊ", "UYỂ");
            put("ỤYNh", "UỴNh");
            put("ỤyNH", "UỵNH");
            put("ỊêU", "IệU");
            put("Òay", "Oày");
            put("ủÂY", "uẨY");
            put("ỤYT", "UỴT");
            put("ÙÔI", "UỒI");
            put("ỤYN", "UỴN");
            put("ỤYP", "UỴP");
            put("ỤYA", "UỴA");
            put("òai", "oài");
            put("òan", "oàn");
            put("uYẠ", "uỴA");
            put("ÚyNh", "UýNh");
            put("uYẢ", "uỶA");
            put("ụYnH", "uỴnH");
            put("ỤyNh", "UỵNh");
            put("ịÊU", "iỆU");
            put("òay", "oày");
            put("ÙÔi", "UỒi");
            put("ùÔI", "uỒI");
            put("ÓEC", "OÉC");
            put("ụyt", "uỵt");
            put("ÚYNh", "UÝNh");
            put("ÚyNH", "UýNH");
            put("ÓEP", "OÉP");
            put("ÓEN", "OÉN");
            put("ÓET", "OÉT");
            put("ụyp", "uỵp");
            put("úynh", "uýnh");
            put("ủyê", "uyể");
            put("ụyn", "uỵn");
            put("ÓEc", "OÉc");
            put("óEC", "oÉC");
            put("ÒeN", "OèN");
            put("ụya", "uỵa");
            put("ưƠÌ", "ưỜI");
            put("ưƠÍ", "ưỚI");
            put("ÚYNH", "UÝNH");
            put("ÓEp", "OÉp");
            put("óEP", "oÉP");
            put("ÓEn", "OÉn");
            put("óEN", "oÉN");
            put("ÓEt", "OÉt");
            put("óET", "oÉT");
            put("ụynh", "uỵnh");
            put("ưƠÚ", "ưỚU");
            put("ưƠÙ", "ưỜU");
            put("ỦYn", "UỶn");
            put("Òen", "Oèn");
            put("ỦYa", "UỶa");
            put("ỈêU", "IểU");
            put("ỤYÊ", "UYỆ");
            put("ụÂY", "uẬY");
            put("ựƠU", "ưỢU");
            put("òen", "oèn");
            put("ươí", "ưới");
            put("ũôi", "uỗi");
            put("ươì", "ười");
            put("ỦYNH", "UỶNH");
            put("ỉÊU", "iỂU");
            put("ươù", "ườu");
            put("Ũynh", "Uỹnh");
            put("ựƠI", "ưỢI");
            put("ươú", "ướu");
            put("OAÍ", "OÁI");
            put("OAÌ", "OÀI");
            put("ưƠĨ", "ưỠI");
            put("ỦYNh", "UỶNh");
            put("ỦyNH", "UỷNH");
            put("ÚyA", "UýA");
            put("ụyê", "uyệ");
            put("Ủây", "Uẩy");
            put("OAÝ", "OÁY");
            put("ÚyN", "UýN");
            put("ũYNh", "uỸNh");
            put("ũyNH", "uỹNH");
            put("YêỤ", "YệU");
            put("ÚyP", "UýP");
            put("YêỦ", "YểU");
            put("Yêụ", "Yệu");
            put("ÚyT", "UýT");
            put("Yêủ", "Yểu");
            put("ŨÔI", "UỖI");
            put("OAí", "OÁi");
            put("oAÍ", "oÁI");
            put("OAì", "OÀi");
            put("oAÌ", "oÀI");
            put("ươĩ", "ưỡi");
            put("ỦyNh", "UỷNh");
            put("Úya", "Uýa");
            put("ủYnH", "uỶnH");
            put("IÊỤ", "IỆU");
            put("ỦYê", "UYể");
            put("IÊỦ", "IỂU");
            put("UâỲ", "UầY");
            put("IÊụ", "IỆu");
            put("UâỴ", "UậY");
            put("Ịêu", "Iệu");
            put("IÊủ", "IỂu");
            put("Uâỳ", "Uầy");
            put("UâỶ", "UẩY");
            put("Uâỵ", "Uậy");
            put("ỦâY", "UẩY");
            put("OAý", "OÁy");
            put("oAÝ", "oÁY");
            put("UâỸ", "UẫY");
            put("Uâỷ", "Uẩy");
            put("ỤYt", "UỴt");
            put("Úyn", "Uýn");
            put("Uâỹ", "Uẫy");
            put("ỤYn", "UỴn");
            put("ũYNH", "uỸNH");
            put("ỤYp", "UỴp");
            put("Úyp", "Uýp");
            put("yêủ", "yểu");
            put("yêụ", "yệu");
            put("Úyt", "Uýt");
            put("ŨÔi", "UỖi");
            put("ỤYa", "UỴa");
            put("ưƠŨ", "ưỠU");
            put("úya", "uýa");
            put("iÊỤ", "iỆU");
            put("iÊỦ", "iỂU");
            put("uâỳ", "uầy");
            put("uâỵ", "uậy");
            put("uâỷ", "uẩy");
            put("úyn", "uýn");
            put("UÔÌ", "UỒI");
            put("uâỹ", "uẫy");
            put("UÔÍ", "UỐI");
            put("ữƠU", "ưỠU");
            put("úyp", "uýp");
            put("OAĩ", "OÃi");
            put("úyt", "uýt");
            put("OAĨ", "OÃI");
            put("ỸÊu", "YỄu");
            put("ươũ", "ưỡu");
            put("ủynh", "uỷnh");
            put("ÙYA", "UỲA");
            put("ữƠI", "ưỠI");
            put("UÔì", "UỒi");
            put("uÔÌ", "uỒI");
            put("ÙYN", "UỲN");
            put("UÔí", "UỐi");
            put("uÔÍ", "uỐI");
            put("oAĨ", "oÃI");
            put("ỸÊU", "YỄU");
            put("ÙYa", "UỲa");
            put("ùYA", "uỲA");
            put("ÚyÊ", "UyẾ");
            put("ÙYn", "UỲn");
            put("ùYN", "uỲN");
            put("ŨYnh", "UỸnh");
            put("ŨynH", "UỹnH");
            put("Ụây", "Uậy");
            put("ựơu", "ượu");
            put("Ỉêu", "Iểu");
            put("ỤYê", "UYệ");
            put("Úyê", "Uyế");
            put("UÔĨ", "UỖI");
            put("UÔĩ", "UỖi");
            put("ựơi", "ượi");
            put("ŨYnH", "UỸnH");
            put("ỤâY", "UậY");
            put("ỹêu", "yễu");
            put("úyê", "uyế");
            put("uÔĨ", "uỖI");
            put("ỶÊu", "YỂu");
            put("ửƠU", "ưỞU");
            put("ửƠI", "ưỞI");
            put("ÙYÊ", "UYỀ");
            put("ÚÂY", "UẤY");
            put("ũya", "uỹa");
            put("ỶÊU", "YỂU");
            put("ũyn", "uỹn");
            put("ÙYê", "UYề");
            put("ùYÊ", "uYỀ");
            put("ÝêU", "YếU");
            put("ÚÂy", "UẤy");
            put("úÂY", "uẤY");
            put("ÙâY", "UầY");
            put("ữơu", "ưỡu");
            put("ÍÊU", "IẾU");
            put("ữơi", "ưỡi");
            put("Ýêu", "Yếu");
            put("Ùây", "Uầy");
            put("ÌêU", "IềU");
            put("ŨYA", "UỸA");
            put("ỷêu", "yểu");
            put("ŨYN", "UỸN");
            put("ÍÊu", "IẾu");
            put("íÊU", "iẾU");
            put("ỳêu", "yều");
            put("ýêu", "yếu");
            put("ùây", "uầy");
            put("ừƠU", "ưỜU");
            put("Ìêu", "Iều");
            put("ŨYa", "UỸa");
            put("ŨYn", "UỸn");
            put("UYÁ", "UÝA");
            put("UYÀ", "UỲA");
            put("UYÃ", "UỸA");
            put("ừƠI", "ưỜI");
            put("UÝÊ", "UYẾ");
            put("ỴÊu", "YỆu");
            put("ìêu", "iều");
            put("UYá", "UÝa");
            put("uYÁ", "uÝA");
            put("UYà", "UỲa");
            put("uYÀ", "uỲA");
            put("UYã", "UỸa");
            put("uYÃ", "uỸA");
            put("ũyê", "uyễ");
            put("UÝê", "UYế");
            put("uÝÊ", "uYẾ");
            put("ỴÊU", "YỆU");
            put("ửơu", "ưởu");
            put("ửơi", "ưởi");
            put("ỵêu", "yệu");
            put("ŨYÊ", "UYỄ");
            put("ÚYch", "UÝch");
            put("ÚycH", "UýcH");
            put("ũÂY", "uẪY");
            put("ỎAI", "OẢI");
            put("ỎAN", "OẢN");
            put("ƯƠỈ", "ƯỞI");
            put("úYCh", "uÝCh");
            put("Oaỉ", "Oải");
            put("ỤYCH", "UỴCH");
            put("úyCH", "uýCH");
            put("OaỈ", "OảI");
            put("Oaị", "Oại");
            put("OaỊ", "OạI");
            put("ŨâY", "UẫY");
            put("ŨYê", "UYễ");
            put("ƯƠị", "ƯỢi");
            put("ƯƠỉ", "ƯỞi");
            put("ƯƠỊ", "ƯỢI");
            put("ÚYcH", "UÝcH");
            put("ứƠI", "ưỚI");
            put("ỲÊu", "YỀu");
            put("ứƠU", "ưỚU");
            put("Ủôi", "Uổi");
            put("ƯƠủ", "ƯỞu");
            put("ƯơỈ", "ƯởI");
            put("Ươỉ", "Ưởi");
            put("ƯƠụ", "ƯỢu");
            put("ƯƠỦ", "ƯỞU");
            put("ỏay", "oảy");
            put("ƯƠỤ", "ƯỢU");
            put("úYCH", "uÝCH");
            put("oaỉ", "oải");
            put("ỤYCh", "UỴCh");
            put("ỤyCH", "UỵCH");
            put("oaị", "oại");
            put("Ũây", "Uẫy");
            put("ƯơỊ", "ƯợI");
            put("Ươị", "Ượi");
            put("Oaỳ", "Oày");
            put("OaỲ", "OàY");
            put("Oaỵ", "Oạy");
            put("OaỴ", "OạY");
            put("ỏai", "oải");
            put("Oaỷ", "Oảy");
            put("OaỶ", "OảY");
            put("Oaỹ", "Oãy");
            put("OaỸ", "OãY");
            put("YêÚ", "YếU");
            put("YêÙ", "YềU");
            put("ỲÊU", "YỀU");
            put("ỏan", "oản");
            put("ỦôI", "UổI");
            put("UâÝ", "UấY");
            put("ƯơỦ", "ƯởU");
            put("Ươủ", "Ưởu");
            put("ƯơỤ", "ƯợU");
            put("Ươụ", "Ượu");
            put("ụYcH", "uỴcH");
            put("ỤyCh", "UỵCh");
            put("IÊÚ", "IẾU");
            put("IÊÙ", "IỀU");
            put("oaỳ", "oày");
            put("oaỵ", "oạy");
            put("oaỷ", "oảy");
            put("oaỹ", "oãy");
            put("ừơi", "ười");
            put("ủÔI", "uỔI");
            put("Yêú", "Yếu");
            put("UôỈ", "UổI");
            put("Yêù", "Yều");
            put("UôỊ", "UộI");
            put("ừơu", "ườu");
            put("Uôỉ", "Uổi");
            put("Uôị", "Uội");
            put("Uâý", "Uấy");
            put("IÊú", "IẾu");
            put("iÊÚ", "iẾU");
            put("IÊù", "IỀu");
            put("iÊÙ", "iỀU");
            put("ỎEN", "OẺN");
            put("ỌAI", "OẠI");
            put("yêú", "yếu");
            put("ỌAP", "OẠP");
            put("yêù", "yều");
            put("ỌAN", "OẠN");
            put("uôỉ", "uổi");
            put("ỌAT", "OẠT");
            put("uôị", "uội");
            put("uâý", "uấy");
            put("ụych", "uỵch");
            put("ỌAC", "OẠC");
            put("ÕaI", "OãI");
            put("ÕaN", "OãN");
            put("Ụôi", "Uội");
            put("ÕaY", "OãY");
            put("ĩÊU", "iỄU");
            put("ọat", "oạt");
            put("ọay", "oạy");
            put("Õai", "Oãi");
            put("Õan", "Oãn");
            put("ọai", "oại");
            put("ọan", "oạn");
            put("ỏen", "oẻn");
            put("ỤôI", "UộI");
            put("Õay", "Oãy");
            put("ọap", "oạp");
            put("ỎAy", "OẢy");
            put("YêŨ", "YễU");
            put("ĨêU", "IễU");
            put("Yêũ", "Yễu");
            put("ọac", "oạc");
            put("õai", "oãi");
            put("Úych", "Uých");
            put("õan", "oãn");
            put("ỎAi", "OẢi");
            put("ứơi", "ưới");
            put("IÊŨ", "IỄU");
            put("ỎAn", "OẢn");
            put("IÊũ", "IỄu");
            put("ứơu", "ướu");
            put("õay", "oãy");
            put("ụÔI", "uỘI");
            put("ỎAY", "OẢY");
            put("Ĩêu", "Iễu");
            put("yêũ", "yễu");
            put("ỌEP", "OẸP");
            put("ỌEN", "OẸN");
            put("iÊŨ", "iỄU");
            put("ỌET", "OẸT");
            put("Ủyn", "Uỷn");
            put("ÓaC", "OáC");
            put("ÓaI", "OáI");
            put("ÙYNh", "UỲNh");
            put("ỌEC", "OẸC");
            put("Ủya", "Uỷa");
            put("ÕeN", "OẽN");
            put("ÙyNH", "UỳNH");
            put("ÓaP", "OáP");
            put("ÓaN", "OáN");
            put("ÓaT", "OáT");
            put("ÓaY", "OáY");
            put("ùynh", "uỳnh");
            put("ỦyN", "UỷN");
            put("Óac", "Oác");
            put("Óai", "Oái");
            put("ÙYNH", "UỲNH");
            put("ỦyA", "UỷA");
            put("Õen", "Oẽn");
            put("Óap", "Oáp");
            put("Óan", "Oán");
            put("ỤYnH", "UỴnH");
            put("ọen", "oẹn");
            put("Óat", "Oát");
            put("ủYN", "uỶN");
            put("Óay", "Oáy");
            put("ọep", "oẹp");
            put("ÚÔI", "UỐI");
            put("ọet", "oẹt");
            put("óac", "oác");
            put("ỌAy", "OẠy");
            put("óai", "oái");
            put("ọec", "oẹc");
            put("ủYA", "uỶA");
            put("Uyạ", "Uỵa");
            put("õen", "oẽn");
            put("UyẠ", "UỵA");
            put("Uyả", "Uỷa");
            put("UyẢ", "UỷA");
            put("óap", "oáp");
            put("óan", "oán");
            put("ỤYnh", "UỴnh");
            put("ỤynH", "UỵnH");
            put("ỎEn", "OẺn");
            put("óat", "oát");
            put("ỌAi", "OẠi");
            put("ùYnH", "uỲnH");
            put("óay", "oáy");
            put("ỌAp", "OẠp");
            put("ỌAn", "OẠn");
            put("ÚÔi", "UỐi");
            put("úÔI", "uỐI");
            put("ỌAt", "OẠt");
            put("ÙôI", "UồI");
            put("ỌAY", "OẠY");
            put("ÒAI", "OÀI");
            put("uyạ", "uỵa");
            put("ÒAN", "OÀN");
            put("ỌAc", "OẠc");
            put("uyả", "uỷa");
            put("Ủyê", "Uyể");
            put("Ụynh", "Uỵnh");
            put("ÒAY", "OÀY");
            put("ủây", "uẩy");
            put("Ụyt", "Uỵt");
            put("Ùôi", "Uồi");
            put("Ụyn", "Uỵn");
            put("Ụyp", "Uỵp");
            put("ÓeC", "OéC");
            put("Ụya", "Uỵa");
            put("ÒAi", "OÀi");
            put("òAI", "oÀI");
            put("ÒAn", "OÀn");
            put("òAN", "oÀN");
            put("ÓeP", "OéP");
            put("ÓeN", "OéN");
            put("ÓeT", "OéT");
            put("ỦyÊ", "UyỂ");
            put("ịêu", "iệu");
            put("ÒAy", "OÀy");
            put("òAY", "oÀY");
            put("ỤyT", "UỵT");
            put("ùôi", "uồi");
            put("ỤyN", "UỵN");
            put("ỤyP", "UỵP");
            put("Óec", "Oéc");
            put("ụYT", "uỴT");
            put("ỤyA", "UỵA");
            put("Úynh", "Uýnh");
            put("Óep", "Oép");
            put("Óen", "Oén");
            put("Óet", "Oét");
            put("ụYNH", "uỴNH");
            put("ụYP", "uỴP");
            put("úyNH", "uýNH");
            put("úYNh", "uÝNh");
            put("ủYÊ", "uYỂ");
            put("ụYN", "uỴN");
            put("óec", "oéc");
            put("ụYA", "uỴA");
            put("ÚYnh", "UÝnh");
            put("ÚynH", "UýnH");
            put("óep", "oép");
            put("óen", "oén");
            put("óet", "oét");
            put("ụYNh", "uỴNh");
            put("ụyNH", "uỵNH");
            put("ỌEp", "OẸp");
            put("ỌEn", "OẸn");
            put("ỌEt", "OẸt");
            put("úYNH", "uÝNH");
            put("ÒEN", "OÈN");
            put("ỌEc", "OẸc");
            put("ÚYnH", "UÝnH");
            put("ÙyNh", "UỳNh");
            put("ỦYnH", "UỶnH");
            put("Ụyê", "Uyệ");
            put("ụây", "uậy");
            put("ŨyNh", "UỹNh");
            put("ũYnH", "uỸnH");
            put("ÒEn", "OÈn");
            put("òEN", "oÈN");
            put("ƯƠÍ", "ƯỚI");
            put("OaÍ", "OáI");
            put("ũÔI", "uỖI");
            put("OaÌ", "OàI");
            put("ƯƠÌ", "ƯỜI");
            put("ỦYnh", "UỶnh");
            put("ỦynH", "UỷnH");
            put("ỤyÊ", "UyỆ");
            put("ỉêu", "iểu");
            put("ỦÂy", "UẨy");
            put("OaÝ", "OáY");
            put("ƯƠÙ", "ƯỜU");
            put("ŨyNH", "UỹNH");
            put("ƯƠÚ", "ƯỚU");
            put("ŨYNh", "UỸNh");
            put("ŨôI", "UỗI");
            put("ƯƠí", "ƯỚi");
            put("Oaí", "Oái");
            put("Oaì", "Oài");
            put("ƯơÌ", "ƯờI");
            put("ƯơÍ", "ƯớI");
            put("ƯƠì", "ƯỜi");
            put("Ủynh", "Uỷnh");
            put("ƯơÙ", "ƯờU");
            put("ụYÊ", "uYỆ");
            put("IêỤ", "IệU");
            put("IêỦ", "IểU");
            put("Iêụ", "Iệu");
            put("ỊÊu", "IỆu");
            put("Iêủ", "Iểu");
            put("ỦÂY", "UẨY");
            put("Oaý", "Oáy");
            put("ƯƠù", "ƯỜu");
            put("ƯơÚ", "ƯớU");
            put("ƯƠú", "ƯỚu");
            put("ũynh", "uỹnh");
            put("Ũôi", "Uỗi");
            put("oaí", "oái");
            put("oaì", "oài");
            put("Ươì", "Ười");
            put("Ươí", "Ưới");
            put("Ươù", "Ườu");
            put("ÚYA", "UÝA");
            put("iêụ", "iệu");
            put("ỊÊU", "IỆU");
            put("iêủ", "iểu");
            put("oaý", "oáy");
            put("ÚYN", "UÝN");
            put("UôÌ", "UồI");
            put("Ươú", "Ướu");
            put("UôÍ", "UốI");
            put("ƯƠĨ", "ƯỠI");
            put("YÊỤ", "YỆU");
            put("ÚYP", "UÝP");
            put("YÊỦ", "YỂU");
            put("YÊụ", "YỆu");
            put("Oaĩ", "Oãi");
            put("ÚYT", "UÝT");
            put("YÊủ", "YỂu");
            put("OaĨ", "OãI");
            put("ƯƠĩ", "ƯỠi");
            put("ÚYa", "UÝa");
            put("úYA", "uÝA");
            put("ủYNH", "uỶNH");
            put("ÙyA", "UỳA");
            put("UÂỲ", "UẦY");
            put("UÂỴ", "UẬY");
            put("UÂỳ", "UẦy");
            put("UÂỶ", "UẨY");
            put("UÂỵ", "UẬy");
            put("UÂỸ", "UẪY");
            put("UÂỷ", "UẨy");
            put("ÚYn", "UÝn");
            put("úYN", "uÝN");
            put("Uôì", "Uồi");
            put("UÂỹ", "UẪy");
            put("ÙyN", "UỳN");
            put("Uôí", "Uối");
            put("ƯơĨ", "ƯỡI");
            put("Ựơu", "Ượu");
            put("Ươĩ", "Ưỡi");
            put("yÊỤ", "yỆU");
            put("ÚYp", "UÝp");
            put("úYP", "uÝP");
            put("yÊỦ", "yỂU");
            put("oaĩ", "oãi");
            put("ÚYt", "UÝt");
            put("úYT", "uÝT");
            put("ủYNh", "uỶNh");
            put("ủyNH", "uỷNH");
            put("Ùya", "Uỳa");
            put("uÂỲ", "uẦY");
            put("uÂỴ", "uẬY");
            put("uÂỶ", "uẨY");
            put("uÂỸ", "uẪY");
            put("uôì", "uồi");
            put("Ựơi", "Ượi");
            put("Ùyn", "Uỳn");
            put("ỤÂy", "UẬy");
            put("uôí", "uối");
            put("ỰơU", "ƯợU");
            put("ƯƠŨ", "ƯỠU");
            put("ỰƠu", "ƯỢu");
            put("Ỹêu", "Yễu");
            put("ƯƠũ", "ƯỠu");
            put("ỈÊu", "IỂu");
            put("ùya", "uỳa");
            put("UôĨ", "UỗI");
            put("Uôĩ", "Uỗi");
            put("ỰơI", "ƯợI");
            put("ùyn", "uỳn");
            put("ỰƠi", "ƯỢi");
            put("ỤÂY", "UẬY");
            put("ŨYNH", "UỸNH");
            put("ƯơŨ", "ƯỡU");
            put("Ươũ", "Ưỡu");
            put("ỰƠU", "ƯỢU");
            put("ỸêU", "YễU");
            put("ỈÊU", "IỂU");
            put("ÚYÊ", "UYẾ");
            put("uôĩ", "uỗi");
            put("ỰƠI", "ƯỢI");
            put("ỹÊU", "yỄU");
            put("ÚYê", "UYế");
            put("úYÊ", "uYẾ");
            put("ÙyÊ", "UyỀ");
            put("ÚâY", "UấY");
            put("Ữơu", "Ưỡu");
            put("Ữơi", "Ưỡi");
            put("Ùyê", "Uyề");
            put("Úây", "Uấy");
            put("ũYA", "uỸA");
            put("Ỷêu", "Yểu");
            put("ỮơU", "ƯỡU");
            put("ỮƠu", "ƯỠu");
            put("ũYN", "uỸN");
            put("ÍêU", "IếU");
            put("ỮơI", "ƯỡI");
            put("ỮƠi", "ƯỠi");
            put("ùyê", "uyề");
            put("úây", "uấy");
            put("ŨyA", "UỹA");
            put("ỶêU", "YểU");
            put("ỮƠU", "ƯỠU");
            put("ŨyN", "UỹN");
            put("Íêu", "Iếu");
            put("ỮƠI", "ƯỠI");
            put("ÝÊU", "YẾU");
            put("ÙÂY", "UẦY");
            put("Ũya", "Uỹa");
            put("ỷÊU", "yỂU");
            put("Ũyn", "Uỹn");
            put("íêu", "iếu");
            put("UyÁ", "UýA");
            put("UyÀ", "UỳA");
            put("UyÃ", "UỹA");
            put("UýÊ", "UyẾ");
            put("ỳÊU", "yỀU");
            put("ÝÊu", "YẾu");
            put("ýÊU", "yẾU");
            put("ÙÂy", "UẦy");
            put("ùÂY", "uẦY");
            put("ÌÊU", "IỀU");
            put("Ửơu", "Ưởu");
            put("Uyá", "Uýa");
            put("Uyà", "Uỳa");
            put("Uyã", "Uỹa");
            put("Ửơi", "Ưởi");
            put("Uýê", "Uyế");
            put("ÌÊu", "IỀu");
            put("ìÊU", "iỀU");
            put("ỬơU", "ƯởU");
            put("ỬƠu", "ƯỞu");
            put("uyá", "uýa");
            put("uyà", "uỳa");
            put("uyã", "uỹa");
            put("ũYÊ", "uYỄ");
            put("ỬơI", "ƯởI");
            put("ỬƠi", "ƯỞi");
            put("uýê", "uyế");
            put("Ỵêu", "Yệu");
            put("ỬƠU", "ƯỞU");
            put("ŨyÊ", "UyỄ");
            put("ưƠỊ", "ưỢI");
            put("ưƠỈ", "ưỞI");
            put("ỬƠI", "ƯỞI");
            put("ỴêU", "YệU");
            put("ưƠỦ", "ưỞU");
            put("ưƠỤ", "ưỢU");
            put("ỵÊU", "yỆU");
            put("ỤYcH", "UỴcH");
            put("Ũyê", "Uyễ");
            put("ươị", "ượi");
            put("ươỉ", "ưởi");
            put("ÚYCH", "UÝCH");
            put("ũây", "uẫy");
            put("Ỏai", "Oải");
            put("Ỏan", "Oản");
            put("ỦÔi", "UỔi");
            put("ươủ", "ưởu");
            put("ươụ", "ượu");
            put("ỎaY", "OảY");
            put("ỤYch", "UỴch");
            put("ỤycH", "UỵcH");
            put("úych", "uých");
            put("ỎaI", "OảI");
            put("Ừơi", "Ười");
            put("ỎaN", "OảN");
            put("UỲÊ", "UYỀ");
            put("Ừơu", "Ườu");
            put("ỦÔI", "UỔI");
            put("ỏAY", "oẢY");
            put("OAỉ", "OẢi");
            put("Ụych", "Uỵch");
            put("OAỈ", "OẢI");
            put("OAị", "OẠi");
            put("IêÚ", "IếU");
            put("OAỊ", "OẠI");
            put("IêÙ", "IềU");
            put("ŨÂY", "UẪY");
            put("ỏAI", "oẢI");
            put("ỪơI", "ƯờI");
            put("ỪƠi", "ƯỜi");
            put("UỳÊ", "UyỀ");
            put("uỲÊ", "uYỀ");
            put("UỲê", "UYề");
            put("Ỳêu", "Yều");
            put("ỪơU", "ƯờU");
            put("ỪƠu", "ƯỜu");
            put("ỏAN", "oẢN");
            put("úYcH", "uÝcH");
            put("oAỈ", "oẢI");
            put("Iêú", "Iếu");
            put("oAỊ", "oẠI");
            put("Iêù", "Iều");
            put("ŨÂy", "UẪy");
            put("OAỳ", "OÀy");
            put("OAỲ", "OÀY");
            put("OAỵ", "OẠy");
            put("OAỴ", "OẠY");
            put("OAỷ", "OẢy");
            put("OAỶ", "OẢY");
            put("OAỹ", "OÃy");
            put("OAỸ", "OÃY");
            put("ỪƠI", "ƯỜI");
            put("ủôi", "uổi");
            put("YÊÚ", "YẾU");
            put("Uỳê", "Uyề");
            put("YÊÙ", "YỀU");
            put("ỲêU", "YềU");
            put("ỪƠU", "ƯỜU");
            put("UỴÊ", "UYỆ");
            put("UÂÝ", "UẤY");
            put("ụYCH", "uỴCH");
            put("iêú", "iếu");
            put("iêù", "iều");
            put("oAỲ", "oÀY");
            put("oAỴ", "oẠY");
            put("Ỏen", "Oẻn");
            put("oAỶ", "oẢY");
            put("oAỸ", "oÃY");
            put("Ọai", "Oại");
            put("YÊú", "YẾu");
            put("yÊÚ", "yẾU");
            put("UÔỈ", "UỔI");
            put("Ọap", "Oạp");
            put("uỳê", "uyề");
            put("YÊù", "YỀu");
            put("yÊÙ", "yỀU");
            put("UÔỊ", "UỘI");
            put("Ọan", "Oạn");
            put("UÔỉ", "UỔi");
            put("Ọat", "Oạt");
            put("UÔị", "UỘi");
            put("ỤÔi", "UỘi");
            put("UỵÊ", "UyỆ");
            put("uỴÊ", "uYỆ");
            put("UỴê", "UYệ");
            put("UÂý", "UẤy");
            put("uÂÝ", "uẤY");
            put("ụyCH", "uỵCH");
            put("ụYCh", "uỴCh");
            put("ỌaY", "OạY");
            put("Ọac", "Oạc");
            put("ỎeN", "OẻN");
            put("Ứơi", "Ưới");
            put("ỌaI", "OạI");
            put("uÔỈ", "uỔI");
            put("ỌaP", "OạP");
            put("Ứơu", "Ướu");
            put("uÔỊ", "uỘI");
            put("ỌaN", "OạN");
            put("ỌaT", "OạT");
            put("UỶÊ", "UYỂ");
            put("ỤÔI", "UỘI");
            put("Uỵê", "Uyệ");
            put("ĩêu", "iễu");
            put("ọAT", "oẠT");
            put("ọAY", "oẠY");
            put("ỌaC", "OạC");
            put("ÕAI", "OÃI");
            put("ÚyCh", "UýCh");
            put("ÕAN", "OÃN");
            put("ỨơI", "ƯớI");
            put("ỨƠi", "ƯỚi");
            put("ọAI", "oẠI");
            put("IêŨ", "IễU");
            put("ỨơU", "ƯớU");
            put("ọAN", "oẠN");
            put("Iêũ", "Iễu");
            put("ỨƠu", "ƯỚu");
            put("ỏEN", "oẺN");
            put("UỷÊ", "UyỂ");
            put("uỶÊ", "uYỂ");
            put("UỶê", "UYể");
            put("ÕAY", "OÃY");
            put("ọAP", "oẠP");
            put("uỵê", "uyệ");
            put("ọAC", "oẠC");
            put("ÕAi", "OÃi");
            put("õAI", "oÃI");
            put("ÚYCh", "UÝCh");
            put("ÚyCH", "UýCH");
            put("ÕAn", "OÃn");
            put("õAN", "oÃN");
            put("UỸÊ", "UYỄ");
            put("ỨƠI", "ƯỚI");
            put("iêũ", "iễu");
            put("ỨƠU", "ƯỚU");
            put("Uỷê", "Uyể");
            put("ÕAy", "OÃy");
            put("õAY", "oÃY");
            put("ụôi", "uội");
            put("Ỏay", "Oảy");
            put("YÊŨ", "YỄU");
            put("ĨÊU", "IỄU");
            put("YÊũ", "YỄu");
        }
    };

    public final static Map<String, String> VOWAL_AUTO_CORRECT_STEP_3 = new HashMap<String, String>() {
        {
            put("QỤY", "QUỴ");
            put("QŨY", "QUỸ");
            put("GỈA", "GIẢ");
            put("QũA", "QuÃ");
            put("QụA", "QuẠ");
            put("QỤa", "QUạ");
            put("QŨa", "QUã");
            put("qŨA", "qUÃ");
            put("qỤA", "qUẠ");
            put("QũI", "QuĨ");
            put("GỈU", "GIỦ");
            put("QụI", "QuỊ");
            put("QỤi", "QUị");
            put("gĩu", "giũ");
            put("QŨi", "QUĩ");
            put("qŨI", "qUĨ");
            put("qỤI", "qUỊ");
            put("GỉA", "GiẢ");
            put("QũY", "QuỸ");
            put("QụY", "QuỴ");
            put("QỤy", "QUỵ");
            put("QŨy", "QUỹ");
            put("qŨY", "qUỸ");
            put("qỤY", "qUỴ");
            put("GỈa", "GIả");
            put("gỈA", "gIẢ");
            put("Qũa", "Quã");
            put("QỦA", "QUẢ");
            put("Qụa", "Quạ");
            put("Qũi", "Quĩ");
            put("QỦI", "QUỈ");
            put("GỈu", "GIủ");
            put("Qụi", "Quị");
            put("gỈU", "gIỦ");
            put("GỉU", "GiỦ");
            put("GỊA", "GIẠ");
            put("Gỉa", "Giả");
            put("Qũy", "Quỹ");
            put("QỦY", "QUỶ");
            put("Qụy", "Quỵ");
            put("qũa", "quã");
            put("qụa", "quạ");
            put("QỦa", "QUả");
            put("qỦA", "qUẢ");
            put("QủA", "QuẢ");
            put("qũi", "quĩ");
            put("qụi", "quị");
            put("QỦi", "QUỉ");
            put("qỦI", "qUỈ");
            put("GỊU", "GIỤ");
            put("QủI", "QuỈ");
            put("Gỉu", "Giủ");
            put("GịA", "GiẠ");
            put("GỊa", "GIạ");
            put("gỉa", "giả");
            put("gỊA", "gIẠ");
            put("GìA", "GiÀ");
            put("qũy", "quỹ");
            put("qụy", "quỵ");
            put("QỦy", "QUỷ");
            put("qỦY", "qUỶ");
            put("QủY", "QuỶ");
            put("Qủa", "Quả");
            put("GìU", "GiÙ");
            put("GịU", "GiỤ");
            put("GỊu", "GIụ");
            put("gỉu", "giủ");
            put("Qủi", "Quỉ");
            put("gỊU", "gIỤ");
            put("QùA", "QuÀ");
            put("Gịa", "Giạ");
            put("GíA", "GiÁ");
            put("GÌA", "GIÀ");
            put("Gìa", "Già");
            put("QùI", "QuÌ");
            put("Qủy", "Quỷ");
            put("GíU", "GiÚ");
            put("qủa", "quả");
            put("QùY", "QuỲ");
            put("GÌU", "GIÙ");
            put("Gìu", "Giù");
            put("Gịu", "Giụ");
            put("qủi", "quỉ");
            put("gịa", "giạ");
            put("QÙA", "QUÀ");
            put("Qùa", "Quà");
            put("QúA", "QuÁ");
            put("GÍA", "GIÁ");
            put("Gía", "Giá");
            put("gìa", "già");
            put("GÌa", "GIà");
            put("gÌA", "gIÀ");
            put("QÙI", "QUÌ");
            put("Qùi", "Quì");
            put("QúI", "QuÍ");
            put("GĨA", "GIÃ");
            put("qủy", "quỷ");
            put("GÍU", "GIÚ");
            put("Gíu", "Giú");
            put("QÙY", "QUỲ");
            put("Qùy", "Quỳ");
            put("gìu", "giù");
            put("GÌu", "GIù");
            put("gÌU", "gIÙ");
            put("QúY", "QuÝ");
            put("gịu", "giụ");
            put("GĨU", "GIŨ");
            put("qùa", "quà");
            put("QÙa", "QUà");
            put("qÙA", "qUÀ");
            put("QÚA", "QUÁ");
            put("Qúa", "Quá");
            put("gía", "giá");
            put("GÍa", "GIá");
            put("gÍA", "gIÁ");
            put("GĩA", "GiÃ");
            put("qùi", "quì");
            put("QÙi", "QUì");
            put("qÙI", "qUÌ");
            put("QÚI", "QUÍ");
            put("Qúi", "Quí");
            put("GĨa", "GIã");
            put("gĨA", "gIÃ");
            put("gíu", "giú");
            put("GÍu", "GIú");
            put("gÍU", "gIÚ");
            put("qùy", "quỳ");
            put("QÙy", "QUỳ");
            put("qÙY", "qUỲ");
            put("QÚY", "QUÝ");
            put("Qúy", "Quý");
            put("GĩU", "GiŨ");
            put("GĨu", "GIũ");
            put("gĨU", "gIŨ");
            put("qúa", "quá");
            put("QÚa", "QUá");
            put("qÚA", "qUÁ");
            put("Gĩa", "Giã");
            put("qúi", "quí");
            put("QÚi", "QUí");
            put("qÚI", "qUÍ");
            put("QỤA", "QUẠ");
            put("QŨA", "QUÃ");
            put("qúy", "quý");
            put("QÚy", "QUý");
            put("qÚY", "qUÝ");
            put("QỤI", "QUỊ");
            put("Gĩu", "Giũ");
            put("QŨI", "QUĨ");
            put("gĩa", "giã");
        }
    };

    public final static Map<Character, Character> MAP_ACCENT_CHARACTERS = new HashMap<Character, Character>() {
        {
            put('Ă', 'A');
            put('ă', 'a');
            put('Đ', 'D');
            put('đ', 'd');
            put('Ĩ', 'I');
            put('ĩ', 'i');
            put('Ũ', 'U');
            put('ũ', 'u');
            put('Ạ', 'A');
            put('Ơ', 'O');
            put('ạ', 'a');
            put('ơ', 'o');
            put('Ả', 'A');
            put('ả', 'a');
            put('Ấ', 'A');
            put('ấ', 'a');
            put('Ầ', 'A');
            put('ầ', 'a');
            put('Ẩ', 'A');
            put('ẩ', 'a');
            put('Ẫ', 'A');
            put('ẫ', 'a');
            put('Ậ', 'A');
            put('ậ', 'a');
            put('Ắ', 'A');
            put('ắ', 'a');
            put('Ư', 'U');
            put('ư', 'u');
            put('Ằ', 'A');
            put('ằ', 'a');
            put('Ẳ', 'A');
            put('ẳ', 'a');
            put('Ẵ', 'A');
            put('ẵ', 'a');
            put('Ặ', 'A');
            put('ặ', 'a');
            put('Ẹ', 'E');
            put('ẹ', 'e');
            put('Ẻ', 'E');
            put('ẻ', 'e');
            put('Ẽ', 'E');
            put('ẽ', 'e');
            put('Ế', 'E');
            put('ế', 'e');
            put('À', 'A');
            put('Ề', 'E');
            put('ề', 'e');
            put('Á', 'A');
            put('Â', 'A');
            put('Ể', 'E');
            put('ể', 'e');
            put('Ã', 'A');
            put('Ễ', 'E');
            put('ễ', 'e');
            put('Ệ', 'E');
            put('ệ', 'e');
            put('Ỉ', 'I');
            put('È', 'E');
            put('ỉ', 'i');
            put('É', 'E');
            put('Ị', 'I');
            put('Ê', 'E');
            put('ị', 'i');
            put('Ì', 'I');
            put('Ọ', 'O');
            put('ọ', 'o');
            put('Í', 'I');
            put('Ỏ', 'O');
            put('ỏ', 'o');
            put('Ố', 'O');
            put('ố', 'o');
            put('Ò', 'O');
            put('Ồ', 'O');
            put('ồ', 'o');
            put('Ó', 'O');
            put('Ô', 'O');
            put('Ổ', 'O');
            put('ổ', 'o');
            put('Õ', 'O');
            put('Ỗ', 'O');
            put('ỗ', 'o');
            put('Ộ', 'O');
            put('ộ', 'o');
            put('Ù', 'U');
            put('Ú', 'U');
            put('Ớ', 'O');
            put('ớ', 'o');
            put('Ờ', 'O');
            put('ờ', 'o');
            put('Ý', 'Y');
            put('Ở', 'O');
            put('ở', 'o');
            put('à', 'a');
            put('Ỡ', 'O');
            put('á', 'a');
            put('ỡ', 'o');
            put('â', 'a');
            put('Ợ', 'O');
            put('ã', 'a');
            put('ợ', 'o');
            put('Ụ', 'U');
            put('ụ', 'u');
            put('Ủ', 'U');
            put('ủ', 'u');
            put('è', 'e');
            put('Ứ', 'U');
            put('ứ', 'u');
            put('é', 'e');
            put('ê', 'e');
            put('Ừ', 'U');
            put('ừ', 'u');
            put('ì', 'i');
            put('Ử', 'U');
            put('ử', 'u');
            put('í', 'i');
            put('Ữ', 'U');
            put('ữ', 'u');
            put('Ự', 'U');
            put('ự', 'u');
            put('ò', 'o');
            put('Ỳ', 'Y');
            put('ỳ', 'y');
            put('ó', 'o');
            put('ô', 'o');
            put('Ỵ', 'Y');
            put('ỵ', 'y');
            put('õ', 'o');
            put('Ỷ', 'Y');
            put('ỷ', 'y');
            put('Ỹ', 'Y');
            put('ù', 'u');
            put('ỹ', 'y');
            put('ú', 'u');
            put('ý', 'y');
        }
    };

}
